// Code generated by wlgen; DO NOT EDIT.
package primaryselection

import (
	"fmt"
	wayland "github.com/bnema/purego-libwayland/protocol/wayland"
	"github.com/bnema/purego-libwayland/server"
	"runtime"
)

var ZwpPrimarySelectionDeviceManagerV1Interface *server.Interface
var ZwpPrimarySelectionDeviceV1Interface *server.Interface
var ZwpPrimarySelectionOfferV1Interface *server.Interface
var ZwpPrimarySelectionSourceV1Interface *server.Interface

func init() {
	ZwpPrimarySelectionDeviceManagerV1Interface = &server.Interface{Name: "zwp_primary_selection_device_manager_v1", Version: 1}
	ZwpPrimarySelectionDeviceV1Interface = &server.Interface{Name: "zwp_primary_selection_device_v1", Version: 1}
	ZwpPrimarySelectionOfferV1Interface = &server.Interface{Name: "zwp_primary_selection_offer_v1", Version: 1}
	ZwpPrimarySelectionSourceV1Interface = &server.Interface{Name: "zwp_primary_selection_source_v1", Version: 1}
	ZwpPrimarySelectionDeviceManagerV1Interface.Requests = []server.Message{
		{Name: "create_source", Signature: "n", Types: []*server.Interface{ZwpPrimarySelectionSourceV1Interface}},
		{Name: "get_device", Signature: "no", Types: []*server.Interface{ZwpPrimarySelectionDeviceV1Interface, wayland.SeatInterface}},
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
	}
	ZwpPrimarySelectionDeviceManagerV1Interface.Events = []server.Message{}
	ZwpPrimarySelectionDeviceV1Interface.Requests = []server.Message{
		{Name: "set_selection", Signature: "?ou", Types: []*server.Interface{ZwpPrimarySelectionSourceV1Interface, nil}},
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
	}
	ZwpPrimarySelectionDeviceV1Interface.Events = []server.Message{
		{Name: "data_offer", Signature: "n", Types: []*server.Interface{ZwpPrimarySelectionOfferV1Interface}},
		{Name: "selection", Signature: "?o", Types: []*server.Interface{ZwpPrimarySelectionOfferV1Interface}},
	}
	ZwpPrimarySelectionOfferV1Interface.Requests = []server.Message{
		{Name: "receive", Signature: "sh", Types: []*server.Interface{nil, nil}},
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
	}
	ZwpPrimarySelectionOfferV1Interface.Events = []server.Message{
		{Name: "offer", Signature: "s", Types: []*server.Interface{nil}},
	}
	ZwpPrimarySelectionSourceV1Interface.Requests = []server.Message{
		{Name: "offer", Signature: "s", Types: []*server.Interface{nil}},
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
	}
	ZwpPrimarySelectionSourceV1Interface.Events = []server.Message{
		{Name: "send", Signature: "sh", Types: []*server.Interface{nil, nil}},
		{Name: "cancelled", Signature: "", Types: []*server.Interface{}},
	}
	if err := server.NewInterfaces(ZwpPrimarySelectionDeviceManagerV1Interface, ZwpPrimarySelectionDeviceV1Interface, ZwpPrimarySelectionOfferV1Interface, ZwpPrimarySelectionSourceV1Interface); err != nil {
		panic(err)
	}
}

// ZwpPrimarySelectionDeviceManagerV1 X primary selection emulation.
type ZwpPrimarySelectionDeviceManagerV1 struct{ *server.Resource }

func WrapZwpPrimarySelectionDeviceManagerV1(r *server.Resource) *ZwpPrimarySelectionDeviceManagerV1 {
	if r == nil {
		return nil
	}
	return &ZwpPrimarySelectionDeviceManagerV1{r}
}

const ZwpPrimarySelectionDeviceManagerV1RequestCreateSource uint32 = 0
const ZwpPrimarySelectionDeviceManagerV1RequestGetDevice uint32 = 1
const ZwpPrimarySelectionDeviceManagerV1RequestDestroy uint32 = 2

// ZwpPrimarySelectionDeviceManagerV1Handler handles zwp_primary_selection_device_manager_v1 requests.
type ZwpPrimarySelectionDeviceManagerV1Handler interface {
	CreateSource(self *ZwpPrimarySelectionDeviceManagerV1, id uint32)
	GetDevice(self *ZwpPrimarySelectionDeviceManagerV1, id uint32, seat *wayland.Seat)
	Destroy(self *ZwpPrimarySelectionDeviceManagerV1)
}

func NewZwpPrimarySelectionDeviceManagerV1(c server.Client, version int32, id uint32, h ZwpPrimarySelectionDeviceManagerV1Handler) (*ZwpPrimarySelectionDeviceManagerV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for zwp_primary_selection_device_manager_v1")
	}
	var self *ZwpPrimarySelectionDeviceManagerV1
	r, err := c.CreateResource(ZwpPrimarySelectionDeviceManagerV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.CreateSource(self, args[0].NewID())
		case 1:
			h.GetDevice(self, args[0].NewID(), wayland.WrapSeat(args[1].Resource()))
		case 2:
			h.Destroy(self)
			self.Destroy()
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapZwpPrimarySelectionDeviceManagerV1(r)
	r.Data = self
	return self, nil
}
func NewZwpPrimarySelectionDeviceManagerV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(ZwpPrimarySelectionDeviceManagerV1Interface, version, bind)
}

// ZwpPrimarySelectionDeviceV1 .
type ZwpPrimarySelectionDeviceV1 struct{ *server.Resource }

func WrapZwpPrimarySelectionDeviceV1(r *server.Resource) *ZwpPrimarySelectionDeviceV1 {
	if r == nil {
		return nil
	}
	return &ZwpPrimarySelectionDeviceV1{r}
}

const ZwpPrimarySelectionDeviceV1RequestSetSelection uint32 = 0
const ZwpPrimarySelectionDeviceV1RequestDestroy uint32 = 1
const ZwpPrimarySelectionDeviceV1EventDataOffer uint32 = 0
const ZwpPrimarySelectionDeviceV1EventSelection uint32 = 1

// ZwpPrimarySelectionDeviceV1Handler handles zwp_primary_selection_device_v1 requests.
type ZwpPrimarySelectionDeviceV1Handler interface {
	SetSelection(self *ZwpPrimarySelectionDeviceV1, source *ZwpPrimarySelectionSourceV1, serial uint32)
	Destroy(self *ZwpPrimarySelectionDeviceV1)
}

func NewZwpPrimarySelectionDeviceV1(c server.Client, version int32, id uint32, h ZwpPrimarySelectionDeviceV1Handler) (*ZwpPrimarySelectionDeviceV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for zwp_primary_selection_device_v1")
	}
	var self *ZwpPrimarySelectionDeviceV1
	r, err := c.CreateResource(ZwpPrimarySelectionDeviceV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.SetSelection(self, WrapZwpPrimarySelectionSourceV1(args[0].Resource()), args[1].Uint())
		case 1:
			h.Destroy(self)
			self.Destroy()
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapZwpPrimarySelectionDeviceV1(r)
	r.Data = self
	return self, nil
}

// SendDataOffer introduce a new wp_primary_selection_offer.
func (self *ZwpPrimarySelectionDeviceV1) SendDataOffer(offer *ZwpPrimarySelectionOfferV1) {
	self.PostEvent(ZwpPrimarySelectionDeviceV1EventDataOffer, server.NewID(resourceOf(offer)))
}

// SendSelection advertise a new primary selection.
func (self *ZwpPrimarySelectionDeviceV1) SendSelection(id *ZwpPrimarySelectionOfferV1) {
	self.PostEvent(ZwpPrimarySelectionDeviceV1EventSelection, server.Object(resourceOf(id)))
}
func NewZwpPrimarySelectionDeviceV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(ZwpPrimarySelectionDeviceV1Interface, version, bind)
}

// ZwpPrimarySelectionOfferV1 offer to transfer primary selection contents.
type ZwpPrimarySelectionOfferV1 struct{ *server.Resource }

func WrapZwpPrimarySelectionOfferV1(r *server.Resource) *ZwpPrimarySelectionOfferV1 {
	if r == nil {
		return nil
	}
	return &ZwpPrimarySelectionOfferV1{r}
}

const ZwpPrimarySelectionOfferV1RequestReceive uint32 = 0
const ZwpPrimarySelectionOfferV1RequestDestroy uint32 = 1
const ZwpPrimarySelectionOfferV1EventOffer uint32 = 0

// ZwpPrimarySelectionOfferV1Handler handles zwp_primary_selection_offer_v1 requests.
type ZwpPrimarySelectionOfferV1Handler interface {
	Receive(self *ZwpPrimarySelectionOfferV1, mimeType string, fd int)
	Destroy(self *ZwpPrimarySelectionOfferV1)
}

func NewZwpPrimarySelectionOfferV1(c server.Client, version int32, id uint32, h ZwpPrimarySelectionOfferV1Handler) (*ZwpPrimarySelectionOfferV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for zwp_primary_selection_offer_v1")
	}
	var self *ZwpPrimarySelectionOfferV1
	r, err := c.CreateResource(ZwpPrimarySelectionOfferV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Receive(self, args[0].String(), args[1].Fd())
		case 1:
			h.Destroy(self)
			self.Destroy()
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapZwpPrimarySelectionOfferV1(r)
	r.Data = self
	return self, nil
}

// SendOffer advertise offered mime type.
func (self *ZwpPrimarySelectionOfferV1) SendOffer(mimeType string) {
	var p runtime.Pinner
	defer p.Unpin()
	self.PostEvent(ZwpPrimarySelectionOfferV1EventOffer, server.String(&p, mimeType, false))
}
func NewZwpPrimarySelectionOfferV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(ZwpPrimarySelectionOfferV1Interface, version, bind)
}

// ZwpPrimarySelectionSourceV1 offer to replace the contents of the primary selection.
type ZwpPrimarySelectionSourceV1 struct{ *server.Resource }

func WrapZwpPrimarySelectionSourceV1(r *server.Resource) *ZwpPrimarySelectionSourceV1 {
	if r == nil {
		return nil
	}
	return &ZwpPrimarySelectionSourceV1{r}
}

const ZwpPrimarySelectionSourceV1RequestOffer uint32 = 0
const ZwpPrimarySelectionSourceV1RequestDestroy uint32 = 1
const ZwpPrimarySelectionSourceV1EventSend uint32 = 0
const ZwpPrimarySelectionSourceV1EventCancelled uint32 = 1

// ZwpPrimarySelectionSourceV1Handler handles zwp_primary_selection_source_v1 requests.
type ZwpPrimarySelectionSourceV1Handler interface {
	Offer(self *ZwpPrimarySelectionSourceV1, mimeType string)
	Destroy(self *ZwpPrimarySelectionSourceV1)
}

func NewZwpPrimarySelectionSourceV1(c server.Client, version int32, id uint32, h ZwpPrimarySelectionSourceV1Handler) (*ZwpPrimarySelectionSourceV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for zwp_primary_selection_source_v1")
	}
	var self *ZwpPrimarySelectionSourceV1
	r, err := c.CreateResource(ZwpPrimarySelectionSourceV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Offer(self, args[0].String())
		case 1:
			h.Destroy(self)
			self.Destroy()
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapZwpPrimarySelectionSourceV1(r)
	r.Data = self
	return self, nil
}

// SendSend send the primary selection contents.
func (self *ZwpPrimarySelectionSourceV1) SendSend(mimeType string, fd int) {
	var p runtime.Pinner
	defer p.Unpin()
	self.PostEvent(ZwpPrimarySelectionSourceV1EventSend, server.String(&p, mimeType, false), server.Fd(fd))
}

// SendCancelled request for primary selection contents was canceled.
func (self *ZwpPrimarySelectionSourceV1) SendCancelled() {
	self.PostEvent(ZwpPrimarySelectionSourceV1EventCancelled)
}
func NewZwpPrimarySelectionSourceV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(ZwpPrimarySelectionSourceV1Interface, version, bind)
}
func resourceOf(v interface{ GetResource() *server.Resource }) *server.Resource {
	if v == nil {
		return nil
	}
	return v.GetResource()
}
func (self *ZwpPrimarySelectionDeviceManagerV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *ZwpPrimarySelectionDeviceV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *ZwpPrimarySelectionOfferV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *ZwpPrimarySelectionSourceV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
