// Code generated by wlgen; DO NOT EDIT.
package wayland

import (
	"fmt"
	"github.com/bnema/purego-libwayland/server"
	"runtime"
)

var DisplayInterface *server.Interface
var RegistryInterface *server.Interface
var CallbackInterface *server.Interface
var CompositorInterface *server.Interface
var ShmPoolInterface *server.Interface
var ShmInterface *server.Interface
var BufferInterface *server.Interface
var DataOfferInterface *server.Interface
var DataSourceInterface *server.Interface
var DataDeviceInterface *server.Interface
var DataDeviceManagerInterface *server.Interface
var ShellInterface *server.Interface
var ShellSurfaceInterface *server.Interface
var SurfaceInterface *server.Interface
var SeatInterface *server.Interface
var PointerInterface *server.Interface
var KeyboardInterface *server.Interface
var TouchInterface *server.Interface
var OutputInterface *server.Interface
var RegionInterface *server.Interface
var SubcompositorInterface *server.Interface
var SubsurfaceInterface *server.Interface
var FixesInterface *server.Interface

func init() {
	DisplayInterface = &server.Interface{Name: "wl_display", Version: 1}
	RegistryInterface = &server.Interface{Name: "wl_registry", Version: 1}
	CallbackInterface = &server.Interface{Name: "wl_callback", Version: 1}
	CompositorInterface = &server.Interface{Name: "wl_compositor", Version: 7}
	ShmPoolInterface = &server.Interface{Name: "wl_shm_pool", Version: 3}
	ShmInterface = &server.Interface{Name: "wl_shm", Version: 3}
	BufferInterface = &server.Interface{Name: "wl_buffer", Version: 1}
	DataOfferInterface = &server.Interface{Name: "wl_data_offer", Version: 4}
	DataSourceInterface = &server.Interface{Name: "wl_data_source", Version: 4}
	DataDeviceInterface = &server.Interface{Name: "wl_data_device", Version: 4}
	DataDeviceManagerInterface = &server.Interface{Name: "wl_data_device_manager", Version: 4}
	ShellInterface = &server.Interface{Name: "wl_shell", Version: 1}
	ShellSurfaceInterface = &server.Interface{Name: "wl_shell_surface", Version: 1}
	SurfaceInterface = &server.Interface{Name: "wl_surface", Version: 7}
	SeatInterface = &server.Interface{Name: "wl_seat", Version: 11}
	PointerInterface = &server.Interface{Name: "wl_pointer", Version: 11}
	KeyboardInterface = &server.Interface{Name: "wl_keyboard", Version: 11}
	TouchInterface = &server.Interface{Name: "wl_touch", Version: 11}
	OutputInterface = &server.Interface{Name: "wl_output", Version: 4}
	RegionInterface = &server.Interface{Name: "wl_region", Version: 7}
	SubcompositorInterface = &server.Interface{Name: "wl_subcompositor", Version: 1}
	SubsurfaceInterface = &server.Interface{Name: "wl_subsurface", Version: 1}
	FixesInterface = &server.Interface{Name: "wl_fixes", Version: 2}
	DisplayInterface.Requests = []server.Message{
		{Name: "sync", Signature: "n", Types: []*server.Interface{CallbackInterface}},
		{Name: "get_registry", Signature: "n", Types: []*server.Interface{RegistryInterface}},
	}
	DisplayInterface.Events = []server.Message{
		{Name: "error", Signature: "ous", Types: []*server.Interface{nil, nil, nil}},
		{Name: "delete_id", Signature: "u", Types: []*server.Interface{nil}},
	}
	RegistryInterface.Requests = []server.Message{
		{Name: "bind", Signature: "usun", Types: []*server.Interface{nil, nil, nil, nil}},
	}
	RegistryInterface.Events = []server.Message{
		{Name: "global", Signature: "usu", Types: []*server.Interface{nil, nil, nil}},
		{Name: "global_remove", Signature: "u", Types: []*server.Interface{nil}},
	}
	CallbackInterface.Requests = []server.Message{}
	CallbackInterface.Events = []server.Message{
		{Name: "done", Signature: "u", Types: []*server.Interface{nil}},
	}
	CompositorInterface.Requests = []server.Message{
		{Name: "create_surface", Signature: "n", Types: []*server.Interface{SurfaceInterface}},
		{Name: "create_region", Signature: "n", Types: []*server.Interface{RegionInterface}},
		{Name: "release", Signature: "7", Types: []*server.Interface{}},
	}
	CompositorInterface.Events = []server.Message{}
	ShmPoolInterface.Requests = []server.Message{
		{Name: "create_buffer", Signature: "niiiiu", Types: []*server.Interface{BufferInterface, nil, nil, nil, nil, nil}},
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
		{Name: "resize", Signature: "i", Types: []*server.Interface{nil}},
	}
	ShmPoolInterface.Events = []server.Message{}
	ShmInterface.Requests = []server.Message{
		{Name: "create_pool", Signature: "nhi", Types: []*server.Interface{ShmPoolInterface, nil, nil}},
		{Name: "release", Signature: "2", Types: []*server.Interface{}},
	}
	ShmInterface.Events = []server.Message{
		{Name: "format", Signature: "u", Types: []*server.Interface{nil}},
	}
	BufferInterface.Requests = []server.Message{
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
	}
	BufferInterface.Events = []server.Message{
		{Name: "release", Signature: "", Types: []*server.Interface{}},
	}
	DataOfferInterface.Requests = []server.Message{
		{Name: "accept", Signature: "u?s", Types: []*server.Interface{nil, nil}},
		{Name: "receive", Signature: "sh", Types: []*server.Interface{nil, nil}},
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
		{Name: "finish", Signature: "3", Types: []*server.Interface{}},
		{Name: "set_actions", Signature: "3uu", Types: []*server.Interface{nil, nil}},
	}
	DataOfferInterface.Events = []server.Message{
		{Name: "offer", Signature: "s", Types: []*server.Interface{nil}},
		{Name: "source_actions", Signature: "3u", Types: []*server.Interface{nil}},
		{Name: "action", Signature: "3u", Types: []*server.Interface{nil}},
	}
	DataSourceInterface.Requests = []server.Message{
		{Name: "offer", Signature: "s", Types: []*server.Interface{nil}},
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
		{Name: "set_actions", Signature: "3u", Types: []*server.Interface{nil}},
	}
	DataSourceInterface.Events = []server.Message{
		{Name: "target", Signature: "?s", Types: []*server.Interface{nil}},
		{Name: "send", Signature: "sh", Types: []*server.Interface{nil, nil}},
		{Name: "cancelled", Signature: "", Types: []*server.Interface{}},
		{Name: "dnd_drop_performed", Signature: "3", Types: []*server.Interface{}},
		{Name: "dnd_finished", Signature: "3", Types: []*server.Interface{}},
		{Name: "action", Signature: "3u", Types: []*server.Interface{nil}},
	}
	DataDeviceInterface.Requests = []server.Message{
		{Name: "start_drag", Signature: "?oo?ou", Types: []*server.Interface{DataSourceInterface, SurfaceInterface, SurfaceInterface, nil}},
		{Name: "set_selection", Signature: "?ou", Types: []*server.Interface{DataSourceInterface, nil}},
		{Name: "release", Signature: "2", Types: []*server.Interface{}},
	}
	DataDeviceInterface.Events = []server.Message{
		{Name: "data_offer", Signature: "n", Types: []*server.Interface{DataOfferInterface}},
		{Name: "enter", Signature: "uoff?o", Types: []*server.Interface{nil, SurfaceInterface, nil, nil, DataOfferInterface}},
		{Name: "leave", Signature: "", Types: []*server.Interface{}},
		{Name: "motion", Signature: "uff", Types: []*server.Interface{nil, nil, nil}},
		{Name: "drop", Signature: "", Types: []*server.Interface{}},
		{Name: "selection", Signature: "?o", Types: []*server.Interface{DataOfferInterface}},
	}
	DataDeviceManagerInterface.Requests = []server.Message{
		{Name: "create_data_source", Signature: "n", Types: []*server.Interface{DataSourceInterface}},
		{Name: "get_data_device", Signature: "no", Types: []*server.Interface{DataDeviceInterface, SeatInterface}},
		{Name: "release", Signature: "4", Types: []*server.Interface{}},
	}
	DataDeviceManagerInterface.Events = []server.Message{}
	ShellInterface.Requests = []server.Message{
		{Name: "get_shell_surface", Signature: "no", Types: []*server.Interface{ShellSurfaceInterface, SurfaceInterface}},
	}
	ShellInterface.Events = []server.Message{}
	ShellSurfaceInterface.Requests = []server.Message{
		{Name: "pong", Signature: "u", Types: []*server.Interface{nil}},
		{Name: "move", Signature: "ou", Types: []*server.Interface{SeatInterface, nil}},
		{Name: "resize", Signature: "ouu", Types: []*server.Interface{SeatInterface, nil, nil}},
		{Name: "set_toplevel", Signature: "", Types: []*server.Interface{}},
		{Name: "set_transient", Signature: "oiiu", Types: []*server.Interface{SurfaceInterface, nil, nil, nil}},
		{Name: "set_fullscreen", Signature: "uu?o", Types: []*server.Interface{nil, nil, OutputInterface}},
		{Name: "set_popup", Signature: "ouoiiu", Types: []*server.Interface{SeatInterface, nil, SurfaceInterface, nil, nil, nil}},
		{Name: "set_maximized", Signature: "?o", Types: []*server.Interface{OutputInterface}},
		{Name: "set_title", Signature: "s", Types: []*server.Interface{nil}},
		{Name: "set_class", Signature: "s", Types: []*server.Interface{nil}},
	}
	ShellSurfaceInterface.Events = []server.Message{
		{Name: "ping", Signature: "u", Types: []*server.Interface{nil}},
		{Name: "configure", Signature: "uii", Types: []*server.Interface{nil, nil, nil}},
		{Name: "popup_done", Signature: "", Types: []*server.Interface{}},
	}
	SurfaceInterface.Requests = []server.Message{
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
		{Name: "attach", Signature: "?oii", Types: []*server.Interface{BufferInterface, nil, nil}},
		{Name: "damage", Signature: "iiii", Types: []*server.Interface{nil, nil, nil, nil}},
		{Name: "frame", Signature: "n", Types: []*server.Interface{CallbackInterface}},
		{Name: "set_opaque_region", Signature: "?o", Types: []*server.Interface{RegionInterface}},
		{Name: "set_input_region", Signature: "?o", Types: []*server.Interface{RegionInterface}},
		{Name: "commit", Signature: "", Types: []*server.Interface{}},
		{Name: "set_buffer_transform", Signature: "2i", Types: []*server.Interface{nil}},
		{Name: "set_buffer_scale", Signature: "3i", Types: []*server.Interface{nil}},
		{Name: "damage_buffer", Signature: "4iiii", Types: []*server.Interface{nil, nil, nil, nil}},
		{Name: "offset", Signature: "5ii", Types: []*server.Interface{nil, nil}},
		{Name: "get_release", Signature: "7n", Types: []*server.Interface{CallbackInterface}},
	}
	SurfaceInterface.Events = []server.Message{
		{Name: "enter", Signature: "o", Types: []*server.Interface{OutputInterface}},
		{Name: "leave", Signature: "o", Types: []*server.Interface{OutputInterface}},
		{Name: "preferred_buffer_scale", Signature: "6i", Types: []*server.Interface{nil}},
		{Name: "preferred_buffer_transform", Signature: "6u", Types: []*server.Interface{nil}},
	}
	SeatInterface.Requests = []server.Message{
		{Name: "get_pointer", Signature: "n", Types: []*server.Interface{PointerInterface}},
		{Name: "get_keyboard", Signature: "n", Types: []*server.Interface{KeyboardInterface}},
		{Name: "get_touch", Signature: "n", Types: []*server.Interface{TouchInterface}},
		{Name: "release", Signature: "5", Types: []*server.Interface{}},
	}
	SeatInterface.Events = []server.Message{
		{Name: "capabilities", Signature: "u", Types: []*server.Interface{nil}},
		{Name: "name", Signature: "2s", Types: []*server.Interface{nil}},
	}
	PointerInterface.Requests = []server.Message{
		{Name: "set_cursor", Signature: "u?oii", Types: []*server.Interface{nil, SurfaceInterface, nil, nil}},
		{Name: "release", Signature: "3", Types: []*server.Interface{}},
	}
	PointerInterface.Events = []server.Message{
		{Name: "enter", Signature: "uoff", Types: []*server.Interface{nil, SurfaceInterface, nil, nil}},
		{Name: "leave", Signature: "uo", Types: []*server.Interface{nil, SurfaceInterface}},
		{Name: "motion", Signature: "uff", Types: []*server.Interface{nil, nil, nil}},
		{Name: "button", Signature: "uuuu", Types: []*server.Interface{nil, nil, nil, nil}},
		{Name: "axis", Signature: "uuf", Types: []*server.Interface{nil, nil, nil}},
		{Name: "frame", Signature: "5", Types: []*server.Interface{}},
		{Name: "axis_source", Signature: "5u", Types: []*server.Interface{nil}},
		{Name: "axis_stop", Signature: "5uu", Types: []*server.Interface{nil, nil}},
		{Name: "axis_discrete", Signature: "5ui", Types: []*server.Interface{nil, nil}},
		{Name: "axis_value120", Signature: "8ui", Types: []*server.Interface{nil, nil}},
		{Name: "axis_relative_direction", Signature: "9uu", Types: []*server.Interface{nil, nil}},
		{Name: "warp", Signature: "11ff", Types: []*server.Interface{nil, nil}},
	}
	KeyboardInterface.Requests = []server.Message{
		{Name: "release", Signature: "3", Types: []*server.Interface{}},
	}
	KeyboardInterface.Events = []server.Message{
		{Name: "keymap", Signature: "uhu", Types: []*server.Interface{nil, nil, nil}},
		{Name: "enter", Signature: "uoa", Types: []*server.Interface{nil, SurfaceInterface, nil}},
		{Name: "leave", Signature: "uo", Types: []*server.Interface{nil, SurfaceInterface}},
		{Name: "key", Signature: "uuuu", Types: []*server.Interface{nil, nil, nil, nil}},
		{Name: "modifiers", Signature: "uuuuu", Types: []*server.Interface{nil, nil, nil, nil, nil}},
		{Name: "repeat_info", Signature: "4ii", Types: []*server.Interface{nil, nil}},
	}
	TouchInterface.Requests = []server.Message{
		{Name: "release", Signature: "3", Types: []*server.Interface{}},
	}
	TouchInterface.Events = []server.Message{
		{Name: "down", Signature: "uuoiff", Types: []*server.Interface{nil, nil, SurfaceInterface, nil, nil, nil}},
		{Name: "up", Signature: "uui", Types: []*server.Interface{nil, nil, nil}},
		{Name: "motion", Signature: "uiff", Types: []*server.Interface{nil, nil, nil, nil}},
		{Name: "frame", Signature: "", Types: []*server.Interface{}},
		{Name: "cancel", Signature: "", Types: []*server.Interface{}},
		{Name: "shape", Signature: "6iff", Types: []*server.Interface{nil, nil, nil}},
		{Name: "orientation", Signature: "6if", Types: []*server.Interface{nil, nil}},
	}
	OutputInterface.Requests = []server.Message{
		{Name: "release", Signature: "3", Types: []*server.Interface{}},
	}
	OutputInterface.Events = []server.Message{
		{Name: "geometry", Signature: "iiiiissi", Types: []*server.Interface{nil, nil, nil, nil, nil, nil, nil, nil}},
		{Name: "mode", Signature: "uiii", Types: []*server.Interface{nil, nil, nil, nil}},
		{Name: "done", Signature: "2", Types: []*server.Interface{}},
		{Name: "scale", Signature: "2i", Types: []*server.Interface{nil}},
		{Name: "name", Signature: "4s", Types: []*server.Interface{nil}},
		{Name: "description", Signature: "4s", Types: []*server.Interface{nil}},
	}
	RegionInterface.Requests = []server.Message{
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
		{Name: "add", Signature: "iiii", Types: []*server.Interface{nil, nil, nil, nil}},
		{Name: "subtract", Signature: "iiii", Types: []*server.Interface{nil, nil, nil, nil}},
	}
	RegionInterface.Events = []server.Message{}
	SubcompositorInterface.Requests = []server.Message{
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
		{Name: "get_subsurface", Signature: "noo", Types: []*server.Interface{SubsurfaceInterface, SurfaceInterface, SurfaceInterface}},
	}
	SubcompositorInterface.Events = []server.Message{}
	SubsurfaceInterface.Requests = []server.Message{
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
		{Name: "set_position", Signature: "ii", Types: []*server.Interface{nil, nil}},
		{Name: "place_above", Signature: "o", Types: []*server.Interface{SurfaceInterface}},
		{Name: "place_below", Signature: "o", Types: []*server.Interface{SurfaceInterface}},
		{Name: "set_sync", Signature: "", Types: []*server.Interface{}},
		{Name: "set_desync", Signature: "", Types: []*server.Interface{}},
	}
	SubsurfaceInterface.Events = []server.Message{}
	FixesInterface.Requests = []server.Message{
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
		{Name: "destroy_registry", Signature: "o", Types: []*server.Interface{RegistryInterface}},
		{Name: "ack_global_remove", Signature: "2ou", Types: []*server.Interface{RegistryInterface, nil}},
	}
	FixesInterface.Events = []server.Message{}
	if err := server.NewInterfaces(DisplayInterface, RegistryInterface, CallbackInterface, CompositorInterface, ShmPoolInterface, ShmInterface, BufferInterface, DataOfferInterface, DataSourceInterface, DataDeviceInterface, DataDeviceManagerInterface, ShellInterface, ShellSurfaceInterface, SurfaceInterface, SeatInterface, PointerInterface, KeyboardInterface, TouchInterface, OutputInterface, RegionInterface, SubcompositorInterface, SubsurfaceInterface, FixesInterface); err != nil {
		panic(err)
	}
}

// Display core global object.
type Display struct{ *server.Resource }

func WrapDisplay(r *server.Resource) *Display {
	if r == nil {
		return nil
	}
	return &Display{r}
}

const DisplayRequestSync uint32 = 0
const DisplayRequestGetRegistry uint32 = 1
const DisplayEventError uint32 = 0
const DisplayEventDeleteId uint32 = 1

// DisplayError global error values.
type DisplayError uint32

const (
	DisplayErrorInvalidObject  DisplayError = 0
	DisplayErrorInvalidMethod  DisplayError = 1
	DisplayErrorNoMemory       DisplayError = 2
	DisplayErrorImplementation DisplayError = 3
)

// DisplayHandler handles wl_display requests.
type DisplayHandler interface {
	Sync(self *Display, callback uint32)
	GetRegistry(self *Display, registry uint32)
}

func NewDisplay(c server.Client, version int32, id uint32, h DisplayHandler) (*Display, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for wl_display")
	}
	var self *Display
	r, err := c.CreateResource(DisplayInterface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Sync(self, args[0].NewID())
		case 1:
			h.GetRegistry(self, args[0].NewID())
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapDisplay(r)
	r.Data = self
	return self, nil
}

// SendError fatal error event.
func (self *Display) SendError(objectId *server.Resource, code uint32, message string) {
	var p runtime.Pinner
	defer p.Unpin()
	self.PostEvent(DisplayEventError, server.Object(objectId), server.Uint(code), server.String(&p, message, false))
}

// SendDeleteId acknowledge object ID deletion.
func (self *Display) SendDeleteId(id uint32) {
	self.PostEvent(DisplayEventDeleteId, server.Uint(id))
}
func NewDisplayGlobal(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(DisplayInterface, version, bind)
}

// Registry global registry object.
type Registry struct{ *server.Resource }

func WrapRegistry(r *server.Resource) *Registry {
	if r == nil {
		return nil
	}
	return &Registry{r}
}

const RegistryRequestBind uint32 = 0
const RegistryEventGlobal uint32 = 0
const RegistryEventGlobalRemove uint32 = 1

// RegistryHandler handles wl_registry requests.
type RegistryHandler interface {
	Bind(self *Registry, name uint32, interfaceName string, version uint32, id uint32)
}

func NewRegistry(c server.Client, version int32, id uint32, h RegistryHandler) (*Registry, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for wl_registry")
	}
	var self *Registry
	r, err := c.CreateResource(RegistryInterface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Bind(self, args[0].Uint(), args[1].String(), args[2].Uint(), args[3].NewID())
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapRegistry(r)
	r.Data = self
	return self, nil
}

// SendGlobal announce global object.
func (self *Registry) SendGlobal(name uint32, interfaceArg string, version uint32) {
	var p runtime.Pinner
	defer p.Unpin()
	self.PostEvent(RegistryEventGlobal, server.Uint(name), server.String(&p, interfaceArg, false), server.Uint(version))
}

// SendGlobalRemove announce removal of global object.
func (self *Registry) SendGlobalRemove(name uint32) {
	self.PostEvent(RegistryEventGlobalRemove, server.Uint(name))
}
func NewRegistryGlobal(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(RegistryInterface, version, bind)
}

// Callback callback object.
type Callback struct{ *server.Resource }

func WrapCallback(r *server.Resource) *Callback {
	if r == nil {
		return nil
	}
	return &Callback{r}
}

const CallbackEventDone uint32 = 0

// CallbackHandler handles wl_callback requests.
type CallbackHandler interface {
}

func NewCallback(c server.Client, version int32, id uint32, h CallbackHandler) (*Callback, error) {
	var self *Callback
	r, err := c.CreateResource(CallbackInterface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapCallback(r)
	r.Data = self
	return self, nil
}

// SendDone done event.
func (self *Callback) SendDone(callbackData uint32) {
	self.PostEvent(CallbackEventDone, server.Uint(callbackData))
}
func NewCallbackGlobal(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(CallbackInterface, version, bind)
}

// Compositor the compositor singleton.
type Compositor struct{ *server.Resource }

func WrapCompositor(r *server.Resource) *Compositor {
	if r == nil {
		return nil
	}
	return &Compositor{r}
}

const CompositorRequestCreateSurface uint32 = 0
const CompositorRequestCreateRegion uint32 = 1
const CompositorRequestRelease uint32 = 2

// CompositorHandler handles wl_compositor requests.
type CompositorHandler interface {
	CreateSurface(self *Compositor, id uint32)
	CreateRegion(self *Compositor, id uint32)
	Release(self *Compositor)
}

func NewCompositor(c server.Client, version int32, id uint32, h CompositorHandler) (*Compositor, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for wl_compositor")
	}
	var self *Compositor
	r, err := c.CreateResource(CompositorInterface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.CreateSurface(self, args[0].NewID())
		case 1:
			h.CreateRegion(self, args[0].NewID())
		case 2:
			h.Release(self)
			self.Destroy()
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapCompositor(r)
	r.Data = self
	return self, nil
}
func NewCompositorGlobal(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(CompositorInterface, version, bind)
}

// ShmPool a shared memory pool.
type ShmPool struct{ *server.Resource }

func WrapShmPool(r *server.Resource) *ShmPool {
	if r == nil {
		return nil
	}
	return &ShmPool{r}
}

const ShmPoolRequestCreateBuffer uint32 = 0
const ShmPoolRequestDestroy uint32 = 1
const ShmPoolRequestResize uint32 = 2

// ShmPoolError wl_shm_pool error values.
type ShmPoolError uint32

const (
	ShmPoolErrorInvalidFormat ShmPoolError = 0
	ShmPoolErrorInvalidStride ShmPoolError = 1
)

// ShmPoolHandler handles wl_shm_pool requests.
type ShmPoolHandler interface {
	CreateBuffer(self *ShmPool, id uint32, offset int32, width int32, height int32, stride int32, format uint32)
	Destroy(self *ShmPool)
	Resize(self *ShmPool, size int32)
}

func NewShmPool(c server.Client, version int32, id uint32, h ShmPoolHandler) (*ShmPool, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for wl_shm_pool")
	}
	var self *ShmPool
	r, err := c.CreateResource(ShmPoolInterface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.CreateBuffer(self, args[0].NewID(), args[1].Int(), args[2].Int(), args[3].Int(), args[4].Int(), args[5].Uint())
		case 1:
			h.Destroy(self)
			self.Destroy()
		case 2:
			h.Resize(self, args[0].Int())
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapShmPool(r)
	r.Data = self
	return self, nil
}
func NewShmPoolGlobal(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(ShmPoolInterface, version, bind)
}

// Shm shared memory support.
type Shm struct{ *server.Resource }

func WrapShm(r *server.Resource) *Shm {
	if r == nil {
		return nil
	}
	return &Shm{r}
}

const ShmRequestCreatePool uint32 = 0
const ShmRequestRelease uint32 = 1
const ShmEventFormat uint32 = 0

// ShmError wl_shm error values.
type ShmError uint32

const (
	ShmErrorInvalidFormat ShmError = 0
	ShmErrorInvalidStride ShmError = 1
	ShmErrorInvalidFd     ShmError = 2
)

// ShmFormat pixel formats.
type ShmFormat uint32

const (
	ShmFormatArgb8888             ShmFormat = 0
	ShmFormatXrgb8888             ShmFormat = 1
	ShmFormatC8                   ShmFormat = 0x20203843
	ShmFormatRgb332               ShmFormat = 0x38424752
	ShmFormatBgr233               ShmFormat = 0x38524742
	ShmFormatXrgb4444             ShmFormat = 0x32315258
	ShmFormatXbgr4444             ShmFormat = 0x32314258
	ShmFormatRgbx4444             ShmFormat = 0x32315852
	ShmFormatBgrx4444             ShmFormat = 0x32315842
	ShmFormatArgb4444             ShmFormat = 0x32315241
	ShmFormatAbgr4444             ShmFormat = 0x32314241
	ShmFormatRgba4444             ShmFormat = 0x32314152
	ShmFormatBgra4444             ShmFormat = 0x32314142
	ShmFormatXrgb1555             ShmFormat = 0x35315258
	ShmFormatXbgr1555             ShmFormat = 0x35314258
	ShmFormatRgbx5551             ShmFormat = 0x35315852
	ShmFormatBgrx5551             ShmFormat = 0x35315842
	ShmFormatArgb1555             ShmFormat = 0x35315241
	ShmFormatAbgr1555             ShmFormat = 0x35314241
	ShmFormatRgba5551             ShmFormat = 0x35314152
	ShmFormatBgra5551             ShmFormat = 0x35314142
	ShmFormatRgb565               ShmFormat = 0x36314752
	ShmFormatBgr565               ShmFormat = 0x36314742
	ShmFormatRgb888               ShmFormat = 0x34324752
	ShmFormatBgr888               ShmFormat = 0x34324742
	ShmFormatXbgr8888             ShmFormat = 0x34324258
	ShmFormatRgbx8888             ShmFormat = 0x34325852
	ShmFormatBgrx8888             ShmFormat = 0x34325842
	ShmFormatAbgr8888             ShmFormat = 0x34324241
	ShmFormatRgba8888             ShmFormat = 0x34324152
	ShmFormatBgra8888             ShmFormat = 0x34324142
	ShmFormatXrgb2101010          ShmFormat = 0x30335258
	ShmFormatXbgr2101010          ShmFormat = 0x30334258
	ShmFormatRgbx1010102          ShmFormat = 0x30335852
	ShmFormatBgrx1010102          ShmFormat = 0x30335842
	ShmFormatArgb2101010          ShmFormat = 0x30335241
	ShmFormatAbgr2101010          ShmFormat = 0x30334241
	ShmFormatRgba1010102          ShmFormat = 0x30334152
	ShmFormatBgra1010102          ShmFormat = 0x30334142
	ShmFormatYuyv                 ShmFormat = 0x56595559
	ShmFormatYvyu                 ShmFormat = 0x55595659
	ShmFormatUyvy                 ShmFormat = 0x59565955
	ShmFormatVyuy                 ShmFormat = 0x59555956
	ShmFormatAyuv                 ShmFormat = 0x56555941
	ShmFormatNv12                 ShmFormat = 0x3231564e
	ShmFormatNv21                 ShmFormat = 0x3132564e
	ShmFormatNv16                 ShmFormat = 0x3631564e
	ShmFormatNv61                 ShmFormat = 0x3136564e
	ShmFormatYuv410               ShmFormat = 0x39565559
	ShmFormatYvu410               ShmFormat = 0x39555659
	ShmFormatYuv411               ShmFormat = 0x31315559
	ShmFormatYvu411               ShmFormat = 0x31315659
	ShmFormatYuv420               ShmFormat = 0x32315559
	ShmFormatYvu420               ShmFormat = 0x32315659
	ShmFormatYuv422               ShmFormat = 0x36315559
	ShmFormatYvu422               ShmFormat = 0x36315659
	ShmFormatYuv444               ShmFormat = 0x34325559
	ShmFormatYvu444               ShmFormat = 0x34325659
	ShmFormatR8                   ShmFormat = 0x20203852
	ShmFormatR16                  ShmFormat = 0x20363152
	ShmFormatRg88                 ShmFormat = 0x38384752
	ShmFormatGr88                 ShmFormat = 0x38385247
	ShmFormatRg1616               ShmFormat = 0x32334752
	ShmFormatGr1616               ShmFormat = 0x32335247
	ShmFormatXrgb16161616f        ShmFormat = 0x48345258
	ShmFormatXbgr16161616f        ShmFormat = 0x48344258
	ShmFormatArgb16161616f        ShmFormat = 0x48345241
	ShmFormatAbgr16161616f        ShmFormat = 0x48344241
	ShmFormatXyuv8888             ShmFormat = 0x56555958
	ShmFormatVuy888               ShmFormat = 0x34325556
	ShmFormatVuy101010            ShmFormat = 0x30335556
	ShmFormatY210                 ShmFormat = 0x30313259
	ShmFormatY212                 ShmFormat = 0x32313259
	ShmFormatY216                 ShmFormat = 0x36313259
	ShmFormatY410                 ShmFormat = 0x30313459
	ShmFormatY412                 ShmFormat = 0x32313459
	ShmFormatY416                 ShmFormat = 0x36313459
	ShmFormatXvyu2101010          ShmFormat = 0x30335658
	ShmFormatXvyu1216161616       ShmFormat = 0x36335658
	ShmFormatXvyu16161616         ShmFormat = 0x38345658
	ShmFormatY0l0                 ShmFormat = 0x304c3059
	ShmFormatX0l0                 ShmFormat = 0x304c3058
	ShmFormatY0l2                 ShmFormat = 0x324c3059
	ShmFormatX0l2                 ShmFormat = 0x324c3058
	ShmFormatYuv4208bit           ShmFormat = 0x38305559
	ShmFormatYuv42010bit          ShmFormat = 0x30315559
	ShmFormatXrgb8888A8           ShmFormat = 0x38415258
	ShmFormatXbgr8888A8           ShmFormat = 0x38414258
	ShmFormatRgbx8888A8           ShmFormat = 0x38415852
	ShmFormatBgrx8888A8           ShmFormat = 0x38415842
	ShmFormatRgb888A8             ShmFormat = 0x38413852
	ShmFormatBgr888A8             ShmFormat = 0x38413842
	ShmFormatRgb565A8             ShmFormat = 0x38413552
	ShmFormatBgr565A8             ShmFormat = 0x38413542
	ShmFormatNv24                 ShmFormat = 0x3432564e
	ShmFormatNv42                 ShmFormat = 0x3234564e
	ShmFormatP210                 ShmFormat = 0x30313250
	ShmFormatP010                 ShmFormat = 0x30313050
	ShmFormatP012                 ShmFormat = 0x32313050
	ShmFormatP016                 ShmFormat = 0x36313050
	ShmFormatAxbxgxrx106106106106 ShmFormat = 0x30314241
	ShmFormatNv15                 ShmFormat = 0x3531564e
	ShmFormatQ410                 ShmFormat = 0x30313451
	ShmFormatQ401                 ShmFormat = 0x31303451
	ShmFormatXrgb16161616         ShmFormat = 0x38345258
	ShmFormatXbgr16161616         ShmFormat = 0x38344258
	ShmFormatArgb16161616         ShmFormat = 0x38345241
	ShmFormatAbgr16161616         ShmFormat = 0x38344241
	ShmFormatC1                   ShmFormat = 0x20203143
	ShmFormatC2                   ShmFormat = 0x20203243
	ShmFormatC4                   ShmFormat = 0x20203443
	ShmFormatD1                   ShmFormat = 0x20203144
	ShmFormatD2                   ShmFormat = 0x20203244
	ShmFormatD4                   ShmFormat = 0x20203444
	ShmFormatD8                   ShmFormat = 0x20203844
	ShmFormatR1                   ShmFormat = 0x20203152
	ShmFormatR2                   ShmFormat = 0x20203252
	ShmFormatR4                   ShmFormat = 0x20203452
	ShmFormatR10                  ShmFormat = 0x20303152
	ShmFormatR12                  ShmFormat = 0x20323152
	ShmFormatAvuy8888             ShmFormat = 0x59555641
	ShmFormatXvuy8888             ShmFormat = 0x59555658
	ShmFormatP030                 ShmFormat = 0x30333050
	ShmFormatRgb161616            ShmFormat = 0x38344752
	ShmFormatBgr161616            ShmFormat = 0x38344742
	ShmFormatR16f                 ShmFormat = 0x48202052
	ShmFormatGr1616f              ShmFormat = 0x48205247
	ShmFormatBgr161616f           ShmFormat = 0x48524742
	ShmFormatR32f                 ShmFormat = 0x46202052
	ShmFormatGr3232f              ShmFormat = 0x46205247
	ShmFormatBgr323232f           ShmFormat = 0x46524742
	ShmFormatAbgr32323232f        ShmFormat = 0x46384241
	ShmFormatNv20                 ShmFormat = 0x3032564e
	ShmFormatNv30                 ShmFormat = 0x3033564e
	ShmFormatS010                 ShmFormat = 0x30313053
	ShmFormatS210                 ShmFormat = 0x30313253
	ShmFormatS410                 ShmFormat = 0x30313453
	ShmFormatS012                 ShmFormat = 0x32313053
	ShmFormatS212                 ShmFormat = 0x32313253
	ShmFormatS412                 ShmFormat = 0x32313453
	ShmFormatS016                 ShmFormat = 0x36313053
	ShmFormatS216                 ShmFormat = 0x36313253
	ShmFormatS416                 ShmFormat = 0x36313453
	ShmFormatXvuy2101010          ShmFormat = 0x30335958
	ShmFormatP230                 ShmFormat = 0x30333250
	ShmFormatT430                 ShmFormat = 0x30333454
	ShmFormatY8                   ShmFormat = 0x59455247
	ShmFormatXyyy2101010          ShmFormat = 0x34415059
)

// ShmHandler handles wl_shm requests.
type ShmHandler interface {
	CreatePool(self *Shm, id uint32, fd int, size int32)
	Release(self *Shm)
}

func NewShm(c server.Client, version int32, id uint32, h ShmHandler) (*Shm, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for wl_shm")
	}
	var self *Shm
	r, err := c.CreateResource(ShmInterface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.CreatePool(self, args[0].NewID(), args[1].Fd(), args[2].Int())
		case 1:
			h.Release(self)
			self.Destroy()
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapShm(r)
	r.Data = self
	return self, nil
}

// SendFormat pixel format description.
func (self *Shm) SendFormat(format uint32) {
	self.PostEvent(ShmEventFormat, server.Uint(format))
}
func NewShmGlobal(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(ShmInterface, version, bind)
}

// Buffer content for a wl_surface.
type Buffer struct{ *server.Resource }

func WrapBuffer(r *server.Resource) *Buffer {
	if r == nil {
		return nil
	}
	return &Buffer{r}
}

const BufferRequestDestroy uint32 = 0
const BufferEventRelease uint32 = 0

// BufferHandler handles wl_buffer requests.
type BufferHandler interface {
	Destroy(self *Buffer)
}

func NewBuffer(c server.Client, version int32, id uint32, h BufferHandler) (*Buffer, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for wl_buffer")
	}
	var self *Buffer
	r, err := c.CreateResource(BufferInterface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Destroy(self)
			self.Destroy()
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapBuffer(r)
	r.Data = self
	return self, nil
}

// SendRelease compositor releases buffer.
func (self *Buffer) SendRelease() {
	self.PostEvent(BufferEventRelease)
}
func NewBufferGlobal(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(BufferInterface, version, bind)
}

// DataOffer offer to transfer data.
type DataOffer struct{ *server.Resource }

func WrapDataOffer(r *server.Resource) *DataOffer {
	if r == nil {
		return nil
	}
	return &DataOffer{r}
}

const DataOfferRequestAccept uint32 = 0
const DataOfferRequestReceive uint32 = 1
const DataOfferRequestDestroy uint32 = 2
const DataOfferRequestFinish uint32 = 3
const DataOfferRequestSetActions uint32 = 4
const DataOfferEventOffer uint32 = 0
const DataOfferEventSourceActions uint32 = 1
const DataOfferEventAction uint32 = 2

// DataOfferError .
type DataOfferError uint32

const (
	DataOfferErrorInvalidFinish     DataOfferError = 0
	DataOfferErrorInvalidActionMask DataOfferError = 1
	DataOfferErrorInvalidAction     DataOfferError = 2
	DataOfferErrorInvalidOffer      DataOfferError = 3
)

// DataOfferHandler handles wl_data_offer requests.
type DataOfferHandler interface {
	Accept(self *DataOffer, serial uint32, mimeType string)
	Receive(self *DataOffer, mimeType string, fd int)
	Destroy(self *DataOffer)
	Finish(self *DataOffer)
	SetActions(self *DataOffer, dndActions uint32, preferredAction uint32)
}

func NewDataOffer(c server.Client, version int32, id uint32, h DataOfferHandler) (*DataOffer, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for wl_data_offer")
	}
	var self *DataOffer
	r, err := c.CreateResource(DataOfferInterface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Accept(self, args[0].Uint(), args[1].String())
		case 1:
			h.Receive(self, args[0].String(), args[1].Fd())
		case 2:
			h.Destroy(self)
			self.Destroy()
		case 3:
			h.Finish(self)
		case 4:
			h.SetActions(self, args[0].Uint(), args[1].Uint())
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapDataOffer(r)
	r.Data = self
	return self, nil
}

// SendOffer advertise offered mime type.
func (self *DataOffer) SendOffer(mimeType string) {
	var p runtime.Pinner
	defer p.Unpin()
	self.PostEvent(DataOfferEventOffer, server.String(&p, mimeType, false))
}

// SendSourceActions notify the source-side available actions (since version 3).
func (self *DataOffer) SendSourceActions(sourceActions uint32) {
	self.PostEvent(DataOfferEventSourceActions, server.Uint(sourceActions))
}

// SendAction notify the selected action (since version 3).
func (self *DataOffer) SendAction(dndAction uint32) {
	self.PostEvent(DataOfferEventAction, server.Uint(dndAction))
}
func NewDataOfferGlobal(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(DataOfferInterface, version, bind)
}

// DataSource offer to transfer data.
type DataSource struct{ *server.Resource }

func WrapDataSource(r *server.Resource) *DataSource {
	if r == nil {
		return nil
	}
	return &DataSource{r}
}

const DataSourceRequestOffer uint32 = 0
const DataSourceRequestDestroy uint32 = 1
const DataSourceRequestSetActions uint32 = 2
const DataSourceEventTarget uint32 = 0
const DataSourceEventSend uint32 = 1
const DataSourceEventCancelled uint32 = 2
const DataSourceEventDndDropPerformed uint32 = 3
const DataSourceEventDndFinished uint32 = 4
const DataSourceEventAction uint32 = 5

// DataSourceError .
type DataSourceError uint32

const (
	DataSourceErrorInvalidActionMask DataSourceError = 0
	DataSourceErrorInvalidSource     DataSourceError = 1
)

// DataSourceHandler handles wl_data_source requests.
type DataSourceHandler interface {
	Offer(self *DataSource, mimeType string)
	Destroy(self *DataSource)
	SetActions(self *DataSource, dndActions uint32)
}

func NewDataSource(c server.Client, version int32, id uint32, h DataSourceHandler) (*DataSource, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for wl_data_source")
	}
	var self *DataSource
	r, err := c.CreateResource(DataSourceInterface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Offer(self, args[0].String())
		case 1:
			h.Destroy(self)
			self.Destroy()
		case 2:
			h.SetActions(self, args[0].Uint())
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapDataSource(r)
	r.Data = self
	return self, nil
}

// SendTarget a target accepts an offered mime type.
func (self *DataSource) SendTarget(mimeType string) {
	var p runtime.Pinner
	defer p.Unpin()
	self.PostEvent(DataSourceEventTarget, server.String(&p, mimeType, true))
}

// SendSend send the data.
func (self *DataSource) SendSend(mimeType string, fd int) {
	var p runtime.Pinner
	defer p.Unpin()
	self.PostEvent(DataSourceEventSend, server.String(&p, mimeType, false), server.Fd(fd))
}

// SendCancelled selection was cancelled.
func (self *DataSource) SendCancelled() {
	self.PostEvent(DataSourceEventCancelled)
}

// SendDndDropPerformed the drag-and-drop operation physically finished (since version 3).
func (self *DataSource) SendDndDropPerformed() {
	self.PostEvent(DataSourceEventDndDropPerformed)
}

// SendDndFinished the drag-and-drop operation concluded (since version 3).
func (self *DataSource) SendDndFinished() {
	self.PostEvent(DataSourceEventDndFinished)
}

// SendAction notify the selected action (since version 3).
func (self *DataSource) SendAction(dndAction uint32) {
	self.PostEvent(DataSourceEventAction, server.Uint(dndAction))
}
func NewDataSourceGlobal(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(DataSourceInterface, version, bind)
}

// DataDevice data transfer device.
type DataDevice struct{ *server.Resource }

func WrapDataDevice(r *server.Resource) *DataDevice {
	if r == nil {
		return nil
	}
	return &DataDevice{r}
}

const DataDeviceRequestStartDrag uint32 = 0
const DataDeviceRequestSetSelection uint32 = 1
const DataDeviceRequestRelease uint32 = 2
const DataDeviceEventDataOffer uint32 = 0
const DataDeviceEventEnter uint32 = 1
const DataDeviceEventLeave uint32 = 2
const DataDeviceEventMotion uint32 = 3
const DataDeviceEventDrop uint32 = 4
const DataDeviceEventSelection uint32 = 5

// DataDeviceError .
type DataDeviceError uint32

const (
	DataDeviceErrorRole       DataDeviceError = 0
	DataDeviceErrorUsedSource DataDeviceError = 1
)

// DataDeviceHandler handles wl_data_device requests.
type DataDeviceHandler interface {
	StartDrag(self *DataDevice, source *DataSource, origin *Surface, icon *Surface, serial uint32)
	SetSelection(self *DataDevice, source *DataSource, serial uint32)
	Release(self *DataDevice)
}

func NewDataDevice(c server.Client, version int32, id uint32, h DataDeviceHandler) (*DataDevice, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for wl_data_device")
	}
	var self *DataDevice
	r, err := c.CreateResource(DataDeviceInterface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.StartDrag(self, WrapDataSource(args[0].Resource()), WrapSurface(args[1].Resource()), WrapSurface(args[2].Resource()), args[3].Uint())
		case 1:
			h.SetSelection(self, WrapDataSource(args[0].Resource()), args[1].Uint())
		case 2:
			h.Release(self)
			self.Destroy()
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapDataDevice(r)
	r.Data = self
	return self, nil
}

// SendDataOffer introduce a new wl_data_offer.
func (self *DataDevice) SendDataOffer(id *DataOffer) {
	self.PostEvent(DataDeviceEventDataOffer, server.NewID(resourceOf(id)))
}

// SendEnter initiate drag-and-drop session.
func (self *DataDevice) SendEnter(serial uint32, surface *Surface, x server.Fixed, y server.Fixed, id *DataOffer) {
	self.PostEvent(DataDeviceEventEnter, server.Uint(serial), server.Object(resourceOf(surface)), server.FixedArg(x), server.FixedArg(y), server.Object(resourceOf(id)))
}

// SendLeave end drag-and-drop session.
func (self *DataDevice) SendLeave() {
	self.PostEvent(DataDeviceEventLeave)
}

// SendMotion drag-and-drop session motion.
func (self *DataDevice) SendMotion(time uint32, x server.Fixed, y server.Fixed) {
	self.PostEvent(DataDeviceEventMotion, server.Uint(time), server.FixedArg(x), server.FixedArg(y))
}

// SendDrop end drag-and-drop session successfully.
func (self *DataDevice) SendDrop() {
	self.PostEvent(DataDeviceEventDrop)
}

// SendSelection advertise new selection.
func (self *DataDevice) SendSelection(id *DataOffer) {
	self.PostEvent(DataDeviceEventSelection, server.Object(resourceOf(id)))
}
func NewDataDeviceGlobal(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(DataDeviceInterface, version, bind)
}

// DataDeviceManager data transfer interface.
type DataDeviceManager struct{ *server.Resource }

func WrapDataDeviceManager(r *server.Resource) *DataDeviceManager {
	if r == nil {
		return nil
	}
	return &DataDeviceManager{r}
}

const DataDeviceManagerRequestCreateDataSource uint32 = 0
const DataDeviceManagerRequestGetDataDevice uint32 = 1
const DataDeviceManagerRequestRelease uint32 = 2

// DataDeviceManagerDndAction drag and drop actions (bitfield).
type DataDeviceManagerDndAction uint32

const (
	DataDeviceManagerDndActionNone DataDeviceManagerDndAction = 0
	DataDeviceManagerDndActionCopy DataDeviceManagerDndAction = 1
	DataDeviceManagerDndActionMove DataDeviceManagerDndAction = 2
	DataDeviceManagerDndActionAsk  DataDeviceManagerDndAction = 4
)

// DataDeviceManagerHandler handles wl_data_device_manager requests.
type DataDeviceManagerHandler interface {
	CreateDataSource(self *DataDeviceManager, id uint32)
	GetDataDevice(self *DataDeviceManager, id uint32, seat *Seat)
	Release(self *DataDeviceManager)
}

func NewDataDeviceManager(c server.Client, version int32, id uint32, h DataDeviceManagerHandler) (*DataDeviceManager, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for wl_data_device_manager")
	}
	var self *DataDeviceManager
	r, err := c.CreateResource(DataDeviceManagerInterface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.CreateDataSource(self, args[0].NewID())
		case 1:
			h.GetDataDevice(self, args[0].NewID(), WrapSeat(args[1].Resource()))
		case 2:
			h.Release(self)
			self.Destroy()
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapDataDeviceManager(r)
	r.Data = self
	return self, nil
}
func NewDataDeviceManagerGlobal(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(DataDeviceManagerInterface, version, bind)
}

// Shell create desktop-style surfaces.
type Shell struct{ *server.Resource }

func WrapShell(r *server.Resource) *Shell {
	if r == nil {
		return nil
	}
	return &Shell{r}
}

const ShellRequestGetShellSurface uint32 = 0

// ShellError .
type ShellError uint32

const (
	ShellErrorRole ShellError = 0
)

// ShellHandler handles wl_shell requests.
type ShellHandler interface {
	GetShellSurface(self *Shell, id uint32, surface *Surface)
}

func NewShell(c server.Client, version int32, id uint32, h ShellHandler) (*Shell, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for wl_shell")
	}
	var self *Shell
	r, err := c.CreateResource(ShellInterface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.GetShellSurface(self, args[0].NewID(), WrapSurface(args[1].Resource()))
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapShell(r)
	r.Data = self
	return self, nil
}
func NewShellGlobal(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(ShellInterface, version, bind)
}

// ShellSurface desktop-style metadata interface.
type ShellSurface struct{ *server.Resource }

func WrapShellSurface(r *server.Resource) *ShellSurface {
	if r == nil {
		return nil
	}
	return &ShellSurface{r}
}

const ShellSurfaceRequestPong uint32 = 0
const ShellSurfaceRequestMove uint32 = 1
const ShellSurfaceRequestResize uint32 = 2
const ShellSurfaceRequestSetToplevel uint32 = 3
const ShellSurfaceRequestSetTransient uint32 = 4
const ShellSurfaceRequestSetFullscreen uint32 = 5
const ShellSurfaceRequestSetPopup uint32 = 6
const ShellSurfaceRequestSetMaximized uint32 = 7
const ShellSurfaceRequestSetTitle uint32 = 8
const ShellSurfaceRequestSetClass uint32 = 9
const ShellSurfaceEventPing uint32 = 0
const ShellSurfaceEventConfigure uint32 = 1
const ShellSurfaceEventPopupDone uint32 = 2

// ShellSurfaceResize edge values for resizing (bitfield).
type ShellSurfaceResize uint32

const (
	ShellSurfaceResizeNone        ShellSurfaceResize = 0
	ShellSurfaceResizeTop         ShellSurfaceResize = 1
	ShellSurfaceResizeBottom      ShellSurfaceResize = 2
	ShellSurfaceResizeLeft        ShellSurfaceResize = 4
	ShellSurfaceResizeTopLeft     ShellSurfaceResize = 5
	ShellSurfaceResizeBottomLeft  ShellSurfaceResize = 6
	ShellSurfaceResizeRight       ShellSurfaceResize = 8
	ShellSurfaceResizeTopRight    ShellSurfaceResize = 9
	ShellSurfaceResizeBottomRight ShellSurfaceResize = 10
)

// ShellSurfaceTransient details of transient behaviour (bitfield).
type ShellSurfaceTransient uint32

const (
	ShellSurfaceTransientInactive ShellSurfaceTransient = 0x1
)

// ShellSurfaceFullscreenMethod different method to set the surface fullscreen.
type ShellSurfaceFullscreenMethod uint32

const (
	ShellSurfaceFullscreenMethodDefault ShellSurfaceFullscreenMethod = 0
	ShellSurfaceFullscreenMethodScale   ShellSurfaceFullscreenMethod = 1
	ShellSurfaceFullscreenMethodDriver  ShellSurfaceFullscreenMethod = 2
	ShellSurfaceFullscreenMethodFill    ShellSurfaceFullscreenMethod = 3
)

// ShellSurfaceHandler handles wl_shell_surface requests.
type ShellSurfaceHandler interface {
	Pong(self *ShellSurface, serial uint32)
	Move(self *ShellSurface, seat *Seat, serial uint32)
	Resize(self *ShellSurface, seat *Seat, serial uint32, edges uint32)
	SetToplevel(self *ShellSurface)
	SetTransient(self *ShellSurface, parent *Surface, x int32, y int32, flags uint32)
	SetFullscreen(self *ShellSurface, method uint32, framerate uint32, output *Output)
	SetPopup(self *ShellSurface, seat *Seat, serial uint32, parent *Surface, x int32, y int32, flags uint32)
	SetMaximized(self *ShellSurface, output *Output)
	SetTitle(self *ShellSurface, title string)
	SetClass(self *ShellSurface, class string)
}

func NewShellSurface(c server.Client, version int32, id uint32, h ShellSurfaceHandler) (*ShellSurface, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for wl_shell_surface")
	}
	var self *ShellSurface
	r, err := c.CreateResource(ShellSurfaceInterface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Pong(self, args[0].Uint())
		case 1:
			h.Move(self, WrapSeat(args[0].Resource()), args[1].Uint())
		case 2:
			h.Resize(self, WrapSeat(args[0].Resource()), args[1].Uint(), args[2].Uint())
		case 3:
			h.SetToplevel(self)
		case 4:
			h.SetTransient(self, WrapSurface(args[0].Resource()), args[1].Int(), args[2].Int(), args[3].Uint())
		case 5:
			h.SetFullscreen(self, args[0].Uint(), args[1].Uint(), WrapOutput(args[2].Resource()))
		case 6:
			h.SetPopup(self, WrapSeat(args[0].Resource()), args[1].Uint(), WrapSurface(args[2].Resource()), args[3].Int(), args[4].Int(), args[5].Uint())
		case 7:
			h.SetMaximized(self, WrapOutput(args[0].Resource()))
		case 8:
			h.SetTitle(self, args[0].String())
		case 9:
			h.SetClass(self, args[0].String())
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapShellSurface(r)
	r.Data = self
	return self, nil
}

// SendPing ping client.
func (self *ShellSurface) SendPing(serial uint32) {
	self.PostEvent(ShellSurfaceEventPing, server.Uint(serial))
}

// SendConfigure suggest resize.
func (self *ShellSurface) SendConfigure(edges uint32, width int32, height int32) {
	self.PostEvent(ShellSurfaceEventConfigure, server.Uint(edges), server.Int(width), server.Int(height))
}

// SendPopupDone popup interaction is done.
func (self *ShellSurface) SendPopupDone() {
	self.PostEvent(ShellSurfaceEventPopupDone)
}
func NewShellSurfaceGlobal(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(ShellSurfaceInterface, version, bind)
}

// Surface an onscreen surface.
type Surface struct{ *server.Resource }

func WrapSurface(r *server.Resource) *Surface {
	if r == nil {
		return nil
	}
	return &Surface{r}
}

const SurfaceRequestDestroy uint32 = 0
const SurfaceRequestAttach uint32 = 1
const SurfaceRequestDamage uint32 = 2
const SurfaceRequestFrame uint32 = 3
const SurfaceRequestSetOpaqueRegion uint32 = 4
const SurfaceRequestSetInputRegion uint32 = 5
const SurfaceRequestCommit uint32 = 6
const SurfaceRequestSetBufferTransform uint32 = 7
const SurfaceRequestSetBufferScale uint32 = 8
const SurfaceRequestDamageBuffer uint32 = 9
const SurfaceRequestOffset uint32 = 10
const SurfaceRequestGetRelease uint32 = 11
const SurfaceEventEnter uint32 = 0
const SurfaceEventLeave uint32 = 1
const SurfaceEventPreferredBufferScale uint32 = 2
const SurfaceEventPreferredBufferTransform uint32 = 3

// SurfaceError wl_surface error values.
type SurfaceError uint32

const (
	SurfaceErrorInvalidScale      SurfaceError = 0
	SurfaceErrorInvalidTransform  SurfaceError = 1
	SurfaceErrorInvalidSize       SurfaceError = 2
	SurfaceErrorInvalidOffset     SurfaceError = 3
	SurfaceErrorDefunctRoleObject SurfaceError = 4
	SurfaceErrorNoBuffer          SurfaceError = 5
)

// SurfaceHandler handles wl_surface requests.
type SurfaceHandler interface {
	Destroy(self *Surface)
	Attach(self *Surface, buffer *Buffer, x int32, y int32)
	Damage(self *Surface, x int32, y int32, width int32, height int32)
	Frame(self *Surface, callback uint32)
	SetOpaqueRegion(self *Surface, region *Region)
	SetInputRegion(self *Surface, region *Region)
	Commit(self *Surface)
	SetBufferTransform(self *Surface, transform int32)
	SetBufferScale(self *Surface, scale int32)
	DamageBuffer(self *Surface, x int32, y int32, width int32, height int32)
	Offset(self *Surface, x int32, y int32)
	GetRelease(self *Surface, callback uint32)
}

func NewSurface(c server.Client, version int32, id uint32, h SurfaceHandler) (*Surface, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for wl_surface")
	}
	var self *Surface
	r, err := c.CreateResource(SurfaceInterface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Destroy(self)
			self.Destroy()
		case 1:
			h.Attach(self, WrapBuffer(args[0].Resource()), args[1].Int(), args[2].Int())
		case 2:
			h.Damage(self, args[0].Int(), args[1].Int(), args[2].Int(), args[3].Int())
		case 3:
			h.Frame(self, args[0].NewID())
		case 4:
			h.SetOpaqueRegion(self, WrapRegion(args[0].Resource()))
		case 5:
			h.SetInputRegion(self, WrapRegion(args[0].Resource()))
		case 6:
			h.Commit(self)
		case 7:
			h.SetBufferTransform(self, args[0].Int())
		case 8:
			h.SetBufferScale(self, args[0].Int())
		case 9:
			h.DamageBuffer(self, args[0].Int(), args[1].Int(), args[2].Int(), args[3].Int())
		case 10:
			h.Offset(self, args[0].Int(), args[1].Int())
		case 11:
			h.GetRelease(self, args[0].NewID())
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapSurface(r)
	r.Data = self
	return self, nil
}

// SendEnter surface enters an output.
func (self *Surface) SendEnter(output *Output) {
	self.PostEvent(SurfaceEventEnter, server.Object(resourceOf(output)))
}

// SendLeave surface leaves an output.
func (self *Surface) SendLeave(output *Output) {
	self.PostEvent(SurfaceEventLeave, server.Object(resourceOf(output)))
}

// SendPreferredBufferScale preferred buffer scale for the surface (since version 6).
func (self *Surface) SendPreferredBufferScale(factor int32) {
	self.PostEvent(SurfaceEventPreferredBufferScale, server.Int(factor))
}

// SendPreferredBufferTransform preferred buffer transform for the surface (since version 6).
func (self *Surface) SendPreferredBufferTransform(transform uint32) {
	self.PostEvent(SurfaceEventPreferredBufferTransform, server.Uint(transform))
}
func NewSurfaceGlobal(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(SurfaceInterface, version, bind)
}

// Seat group of input devices.
type Seat struct{ *server.Resource }

func WrapSeat(r *server.Resource) *Seat {
	if r == nil {
		return nil
	}
	return &Seat{r}
}

const SeatRequestGetPointer uint32 = 0
const SeatRequestGetKeyboard uint32 = 1
const SeatRequestGetTouch uint32 = 2
const SeatRequestRelease uint32 = 3
const SeatEventCapabilities uint32 = 0
const SeatEventName uint32 = 1

// SeatCapability seat capability bitmask (bitfield).
type SeatCapability uint32

const (
	SeatCapabilityPointer  SeatCapability = 1
	SeatCapabilityKeyboard SeatCapability = 2
	SeatCapabilityTouch    SeatCapability = 4
)

// SeatError wl_seat error values.
type SeatError uint32

const (
	SeatErrorMissingCapability SeatError = 0
)

// SeatHandler handles wl_seat requests.
type SeatHandler interface {
	GetPointer(self *Seat, id uint32)
	GetKeyboard(self *Seat, id uint32)
	GetTouch(self *Seat, id uint32)
	Release(self *Seat)
}

func NewSeat(c server.Client, version int32, id uint32, h SeatHandler) (*Seat, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for wl_seat")
	}
	var self *Seat
	r, err := c.CreateResource(SeatInterface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.GetPointer(self, args[0].NewID())
		case 1:
			h.GetKeyboard(self, args[0].NewID())
		case 2:
			h.GetTouch(self, args[0].NewID())
		case 3:
			h.Release(self)
			self.Destroy()
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapSeat(r)
	r.Data = self
	return self, nil
}

// SendCapabilities seat capabilities changed.
func (self *Seat) SendCapabilities(capabilities uint32) {
	self.PostEvent(SeatEventCapabilities, server.Uint(capabilities))
}

// SendName unique identifier for this seat (since version 2).
func (self *Seat) SendName(name string) {
	var p runtime.Pinner
	defer p.Unpin()
	self.PostEvent(SeatEventName, server.String(&p, name, false))
}
func NewSeatGlobal(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(SeatInterface, version, bind)
}

// Pointer pointer input device.
type Pointer struct{ *server.Resource }

func WrapPointer(r *server.Resource) *Pointer {
	if r == nil {
		return nil
	}
	return &Pointer{r}
}

const PointerRequestSetCursor uint32 = 0
const PointerRequestRelease uint32 = 1
const PointerEventEnter uint32 = 0
const PointerEventLeave uint32 = 1
const PointerEventMotion uint32 = 2
const PointerEventButton uint32 = 3
const PointerEventAxis uint32 = 4
const PointerEventFrame uint32 = 5
const PointerEventAxisSource uint32 = 6
const PointerEventAxisStop uint32 = 7
const PointerEventAxisDiscrete uint32 = 8
const PointerEventAxisValue120 uint32 = 9
const PointerEventAxisRelativeDirection uint32 = 10
const PointerEventWarp uint32 = 11

// PointerError .
type PointerError uint32

const (
	PointerErrorRole PointerError = 0
)

// PointerButtonState physical button state.
type PointerButtonState uint32

const (
	PointerButtonStateReleased PointerButtonState = 0
	PointerButtonStatePressed  PointerButtonState = 1
)

// PointerAxis axis types.
type PointerAxis uint32

const (
	PointerAxisVerticalScroll   PointerAxis = 0
	PointerAxisHorizontalScroll PointerAxis = 1
)

// PointerAxisSource axis source types.
type PointerAxisSource uint32

const (
	PointerAxisSourceWheel      PointerAxisSource = 0
	PointerAxisSourceFinger     PointerAxisSource = 1
	PointerAxisSourceContinuous PointerAxisSource = 2
	PointerAxisSourceWheelTilt  PointerAxisSource = 3
)

// PointerAxisRelativeDirection axis relative direction.
type PointerAxisRelativeDirection uint32

const (
	PointerAxisRelativeDirectionIdentical PointerAxisRelativeDirection = 0
	PointerAxisRelativeDirectionInverted  PointerAxisRelativeDirection = 1
)

// PointerHandler handles wl_pointer requests.
type PointerHandler interface {
	SetCursor(self *Pointer, serial uint32, surface *Surface, hotspotX int32, hotspotY int32)
	Release(self *Pointer)
}

func NewPointer(c server.Client, version int32, id uint32, h PointerHandler) (*Pointer, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for wl_pointer")
	}
	var self *Pointer
	r, err := c.CreateResource(PointerInterface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.SetCursor(self, args[0].Uint(), WrapSurface(args[1].Resource()), args[2].Int(), args[3].Int())
		case 1:
			h.Release(self)
			self.Destroy()
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapPointer(r)
	r.Data = self
	return self, nil
}

// SendEnter enter event.
func (self *Pointer) SendEnter(serial uint32, surface *Surface, surfaceX server.Fixed, surfaceY server.Fixed) {
	self.PostEvent(PointerEventEnter, server.Uint(serial), server.Object(resourceOf(surface)), server.FixedArg(surfaceX), server.FixedArg(surfaceY))
}

// SendLeave leave event.
func (self *Pointer) SendLeave(serial uint32, surface *Surface) {
	self.PostEvent(PointerEventLeave, server.Uint(serial), server.Object(resourceOf(surface)))
}

// SendMotion pointer motion event.
func (self *Pointer) SendMotion(time uint32, surfaceX server.Fixed, surfaceY server.Fixed) {
	self.PostEvent(PointerEventMotion, server.Uint(time), server.FixedArg(surfaceX), server.FixedArg(surfaceY))
}

// SendButton pointer button event.
func (self *Pointer) SendButton(serial uint32, time uint32, button uint32, state uint32) {
	self.PostEvent(PointerEventButton, server.Uint(serial), server.Uint(time), server.Uint(button), server.Uint(state))
}

// SendAxis axis event.
func (self *Pointer) SendAxis(time uint32, axis uint32, value server.Fixed) {
	self.PostEvent(PointerEventAxis, server.Uint(time), server.Uint(axis), server.FixedArg(value))
}

// SendFrame end of a pointer event sequence (since version 5).
func (self *Pointer) SendFrame() {
	self.PostEvent(PointerEventFrame)
}

// SendAxisSource axis source event (since version 5).
func (self *Pointer) SendAxisSource(axisSource uint32) {
	self.PostEvent(PointerEventAxisSource, server.Uint(axisSource))
}

// SendAxisStop axis stop event (since version 5).
func (self *Pointer) SendAxisStop(time uint32, axis uint32) {
	self.PostEvent(PointerEventAxisStop, server.Uint(time), server.Uint(axis))
}

// SendAxisDiscrete axis click event (since version 5).
func (self *Pointer) SendAxisDiscrete(axis uint32, discrete int32) {
	self.PostEvent(PointerEventAxisDiscrete, server.Uint(axis), server.Int(discrete))
}

// SendAxisValue120 axis high-resolution scroll event (since version 8).
func (self *Pointer) SendAxisValue120(axis uint32, value120 int32) {
	self.PostEvent(PointerEventAxisValue120, server.Uint(axis), server.Int(value120))
}

// SendAxisRelativeDirection axis relative physical direction event (since version 9).
func (self *Pointer) SendAxisRelativeDirection(axis uint32, direction uint32) {
	self.PostEvent(PointerEventAxisRelativeDirection, server.Uint(axis), server.Uint(direction))
}

// SendWarp pointer warp event (since version 11).
func (self *Pointer) SendWarp(surfaceX server.Fixed, surfaceY server.Fixed) {
	self.PostEvent(PointerEventWarp, server.FixedArg(surfaceX), server.FixedArg(surfaceY))
}
func NewPointerGlobal(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(PointerInterface, version, bind)
}

// Keyboard keyboard input device.
type Keyboard struct{ *server.Resource }

func WrapKeyboard(r *server.Resource) *Keyboard {
	if r == nil {
		return nil
	}
	return &Keyboard{r}
}

const KeyboardRequestRelease uint32 = 0
const KeyboardEventKeymap uint32 = 0
const KeyboardEventEnter uint32 = 1
const KeyboardEventLeave uint32 = 2
const KeyboardEventKey uint32 = 3
const KeyboardEventModifiers uint32 = 4
const KeyboardEventRepeatInfo uint32 = 5

// KeyboardKeymapFormat keyboard mapping format.
type KeyboardKeymapFormat uint32

const (
	KeyboardKeymapFormatNoKeymap KeyboardKeymapFormat = 0
	KeyboardKeymapFormatXkbV1    KeyboardKeymapFormat = 1
)

// KeyboardKeyState physical key state.
type KeyboardKeyState uint32

const (
	KeyboardKeyStateReleased KeyboardKeyState = 0
	KeyboardKeyStatePressed  KeyboardKeyState = 1
	KeyboardKeyStateRepeated KeyboardKeyState = 2
)

// KeyboardHandler handles wl_keyboard requests.
type KeyboardHandler interface {
	Release(self *Keyboard)
}

func NewKeyboard(c server.Client, version int32, id uint32, h KeyboardHandler) (*Keyboard, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for wl_keyboard")
	}
	var self *Keyboard
	r, err := c.CreateResource(KeyboardInterface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Release(self)
			self.Destroy()
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapKeyboard(r)
	r.Data = self
	return self, nil
}

// SendKeymap keyboard mapping.
func (self *Keyboard) SendKeymap(format uint32, fd int, size uint32) {
	self.PostEvent(KeyboardEventKeymap, server.Uint(format), server.Fd(fd), server.Uint(size))
}

// SendEnter enter event.
func (self *Keyboard) SendEnter(serial uint32, surface *Surface, keys []byte) {
	var p runtime.Pinner
	defer p.Unpin()
	self.PostEvent(KeyboardEventEnter, server.Uint(serial), server.Object(resourceOf(surface)), server.Array(&p, keys))
}

// SendLeave leave event.
func (self *Keyboard) SendLeave(serial uint32, surface *Surface) {
	self.PostEvent(KeyboardEventLeave, server.Uint(serial), server.Object(resourceOf(surface)))
}

// SendKey key event.
func (self *Keyboard) SendKey(serial uint32, time uint32, key uint32, state uint32) {
	self.PostEvent(KeyboardEventKey, server.Uint(serial), server.Uint(time), server.Uint(key), server.Uint(state))
}

// SendModifiers modifier and group state.
func (self *Keyboard) SendModifiers(serial uint32, modsDepressed uint32, modsLatched uint32, modsLocked uint32, group uint32) {
	self.PostEvent(KeyboardEventModifiers, server.Uint(serial), server.Uint(modsDepressed), server.Uint(modsLatched), server.Uint(modsLocked), server.Uint(group))
}

// SendRepeatInfo repeat rate and delay (since version 4).
func (self *Keyboard) SendRepeatInfo(rate int32, delay int32) {
	self.PostEvent(KeyboardEventRepeatInfo, server.Int(rate), server.Int(delay))
}
func NewKeyboardGlobal(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(KeyboardInterface, version, bind)
}

// Touch touchscreen input device.
type Touch struct{ *server.Resource }

func WrapTouch(r *server.Resource) *Touch {
	if r == nil {
		return nil
	}
	return &Touch{r}
}

const TouchRequestRelease uint32 = 0
const TouchEventDown uint32 = 0
const TouchEventUp uint32 = 1
const TouchEventMotion uint32 = 2
const TouchEventFrame uint32 = 3
const TouchEventCancel uint32 = 4
const TouchEventShape uint32 = 5
const TouchEventOrientation uint32 = 6

// TouchHandler handles wl_touch requests.
type TouchHandler interface {
	Release(self *Touch)
}

func NewTouch(c server.Client, version int32, id uint32, h TouchHandler) (*Touch, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for wl_touch")
	}
	var self *Touch
	r, err := c.CreateResource(TouchInterface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Release(self)
			self.Destroy()
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapTouch(r)
	r.Data = self
	return self, nil
}

// SendDown touch down event and beginning of a touch sequence.
func (self *Touch) SendDown(serial uint32, time uint32, surface *Surface, id int32, x server.Fixed, y server.Fixed) {
	self.PostEvent(TouchEventDown, server.Uint(serial), server.Uint(time), server.Object(resourceOf(surface)), server.Int(id), server.FixedArg(x), server.FixedArg(y))
}

// SendUp end of a touch event sequence.
func (self *Touch) SendUp(serial uint32, time uint32, id int32) {
	self.PostEvent(TouchEventUp, server.Uint(serial), server.Uint(time), server.Int(id))
}

// SendMotion update of touch point coordinates.
func (self *Touch) SendMotion(time uint32, id int32, x server.Fixed, y server.Fixed) {
	self.PostEvent(TouchEventMotion, server.Uint(time), server.Int(id), server.FixedArg(x), server.FixedArg(y))
}

// SendFrame end of touch frame event.
func (self *Touch) SendFrame() {
	self.PostEvent(TouchEventFrame)
}

// SendCancel touch session cancelled.
func (self *Touch) SendCancel() {
	self.PostEvent(TouchEventCancel)
}

// SendShape update shape of touch point (since version 6).
func (self *Touch) SendShape(id int32, major server.Fixed, minor server.Fixed) {
	self.PostEvent(TouchEventShape, server.Int(id), server.FixedArg(major), server.FixedArg(minor))
}

// SendOrientation update orientation of touch point (since version 6).
func (self *Touch) SendOrientation(id int32, orientation server.Fixed) {
	self.PostEvent(TouchEventOrientation, server.Int(id), server.FixedArg(orientation))
}
func NewTouchGlobal(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(TouchInterface, version, bind)
}

// Output compositor output region.
type Output struct{ *server.Resource }

func WrapOutput(r *server.Resource) *Output {
	if r == nil {
		return nil
	}
	return &Output{r}
}

const OutputRequestRelease uint32 = 0
const OutputEventGeometry uint32 = 0
const OutputEventMode uint32 = 1
const OutputEventDone uint32 = 2
const OutputEventScale uint32 = 3
const OutputEventName uint32 = 4
const OutputEventDescription uint32 = 5

// OutputSubpixel subpixel geometry information.
type OutputSubpixel uint32

const (
	OutputSubpixelUnknown       OutputSubpixel = 0
	OutputSubpixelNone          OutputSubpixel = 1
	OutputSubpixelHorizontalRgb OutputSubpixel = 2
	OutputSubpixelHorizontalBgr OutputSubpixel = 3
	OutputSubpixelVerticalRgb   OutputSubpixel = 4
	OutputSubpixelVerticalBgr   OutputSubpixel = 5
)

// OutputTransform transformation applied to buffer contents.
type OutputTransform uint32

const (
	OutputTransformNormal     OutputTransform = 0
	OutputTransform90         OutputTransform = 1
	OutputTransform180        OutputTransform = 2
	OutputTransform270        OutputTransform = 3
	OutputTransformFlipped    OutputTransform = 4
	OutputTransformFlipped90  OutputTransform = 5
	OutputTransformFlipped180 OutputTransform = 6
	OutputTransformFlipped270 OutputTransform = 7
)

// OutputMode mode information (bitfield).
type OutputMode uint32

const (
	OutputModeCurrent   OutputMode = 0x1
	OutputModePreferred OutputMode = 0x2
)

// OutputHandler handles wl_output requests.
type OutputHandler interface {
	Release(self *Output)
}

func NewOutput(c server.Client, version int32, id uint32, h OutputHandler) (*Output, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for wl_output")
	}
	var self *Output
	r, err := c.CreateResource(OutputInterface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Release(self)
			self.Destroy()
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapOutput(r)
	r.Data = self
	return self, nil
}

// SendGeometry properties of the output.
func (self *Output) SendGeometry(x int32, y int32, physicalWidth int32, physicalHeight int32, subpixel int32, make string, model string, transform int32) {
	var p runtime.Pinner
	defer p.Unpin()
	self.PostEvent(OutputEventGeometry, server.Int(x), server.Int(y), server.Int(physicalWidth), server.Int(physicalHeight), server.Int(subpixel), server.String(&p, make, false), server.String(&p, model, false), server.Int(transform))
}

// SendMode advertise available modes for the output.
func (self *Output) SendMode(flags uint32, width int32, height int32, refresh int32) {
	self.PostEvent(OutputEventMode, server.Uint(flags), server.Int(width), server.Int(height), server.Int(refresh))
}

// SendDone sent all information about output (since version 2).
func (self *Output) SendDone() {
	self.PostEvent(OutputEventDone)
}

// SendScale output scaling properties (since version 2).
func (self *Output) SendScale(factor int32) {
	self.PostEvent(OutputEventScale, server.Int(factor))
}

// SendName name of this output (since version 4).
func (self *Output) SendName(name string) {
	var p runtime.Pinner
	defer p.Unpin()
	self.PostEvent(OutputEventName, server.String(&p, name, false))
}

// SendDescription human-readable description of this output (since version 4).
func (self *Output) SendDescription(description string) {
	var p runtime.Pinner
	defer p.Unpin()
	self.PostEvent(OutputEventDescription, server.String(&p, description, false))
}
func NewOutputGlobal(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(OutputInterface, version, bind)
}

// Region region interface.
type Region struct{ *server.Resource }

func WrapRegion(r *server.Resource) *Region {
	if r == nil {
		return nil
	}
	return &Region{r}
}

const RegionRequestDestroy uint32 = 0
const RegionRequestAdd uint32 = 1
const RegionRequestSubtract uint32 = 2

// RegionHandler handles wl_region requests.
type RegionHandler interface {
	Destroy(self *Region)
	Add(self *Region, x int32, y int32, width int32, height int32)
	Subtract(self *Region, x int32, y int32, width int32, height int32)
}

func NewRegion(c server.Client, version int32, id uint32, h RegionHandler) (*Region, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for wl_region")
	}
	var self *Region
	r, err := c.CreateResource(RegionInterface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Destroy(self)
			self.Destroy()
		case 1:
			h.Add(self, args[0].Int(), args[1].Int(), args[2].Int(), args[3].Int())
		case 2:
			h.Subtract(self, args[0].Int(), args[1].Int(), args[2].Int(), args[3].Int())
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapRegion(r)
	r.Data = self
	return self, nil
}
func NewRegionGlobal(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(RegionInterface, version, bind)
}

// Subcompositor sub-surface compositing.
type Subcompositor struct{ *server.Resource }

func WrapSubcompositor(r *server.Resource) *Subcompositor {
	if r == nil {
		return nil
	}
	return &Subcompositor{r}
}

const SubcompositorRequestDestroy uint32 = 0
const SubcompositorRequestGetSubsurface uint32 = 1

// SubcompositorError .
type SubcompositorError uint32

const (
	SubcompositorErrorBadSurface SubcompositorError = 0
	SubcompositorErrorBadParent  SubcompositorError = 1
)

// SubcompositorHandler handles wl_subcompositor requests.
type SubcompositorHandler interface {
	Destroy(self *Subcompositor)
	GetSubsurface(self *Subcompositor, id uint32, surface *Surface, parent *Surface)
}

func NewSubcompositor(c server.Client, version int32, id uint32, h SubcompositorHandler) (*Subcompositor, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for wl_subcompositor")
	}
	var self *Subcompositor
	r, err := c.CreateResource(SubcompositorInterface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Destroy(self)
			self.Destroy()
		case 1:
			h.GetSubsurface(self, args[0].NewID(), WrapSurface(args[1].Resource()), WrapSurface(args[2].Resource()))
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapSubcompositor(r)
	r.Data = self
	return self, nil
}
func NewSubcompositorGlobal(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(SubcompositorInterface, version, bind)
}

// Subsurface sub-surface interface to a wl_surface.
type Subsurface struct{ *server.Resource }

func WrapSubsurface(r *server.Resource) *Subsurface {
	if r == nil {
		return nil
	}
	return &Subsurface{r}
}

const SubsurfaceRequestDestroy uint32 = 0
const SubsurfaceRequestSetPosition uint32 = 1
const SubsurfaceRequestPlaceAbove uint32 = 2
const SubsurfaceRequestPlaceBelow uint32 = 3
const SubsurfaceRequestSetSync uint32 = 4
const SubsurfaceRequestSetDesync uint32 = 5

// SubsurfaceError .
type SubsurfaceError uint32

const (
	SubsurfaceErrorBadSurface SubsurfaceError = 0
)

// SubsurfaceHandler handles wl_subsurface requests.
type SubsurfaceHandler interface {
	Destroy(self *Subsurface)
	SetPosition(self *Subsurface, x int32, y int32)
	PlaceAbove(self *Subsurface, sibling *Surface)
	PlaceBelow(self *Subsurface, sibling *Surface)
	SetSync(self *Subsurface)
	SetDesync(self *Subsurface)
}

func NewSubsurface(c server.Client, version int32, id uint32, h SubsurfaceHandler) (*Subsurface, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for wl_subsurface")
	}
	var self *Subsurface
	r, err := c.CreateResource(SubsurfaceInterface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Destroy(self)
			self.Destroy()
		case 1:
			h.SetPosition(self, args[0].Int(), args[1].Int())
		case 2:
			h.PlaceAbove(self, WrapSurface(args[0].Resource()))
		case 3:
			h.PlaceBelow(self, WrapSurface(args[0].Resource()))
		case 4:
			h.SetSync(self)
		case 5:
			h.SetDesync(self)
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapSubsurface(r)
	r.Data = self
	return self, nil
}
func NewSubsurfaceGlobal(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(SubsurfaceInterface, version, bind)
}

// Fixes wayland protocol fixes.
type Fixes struct{ *server.Resource }

func WrapFixes(r *server.Resource) *Fixes {
	if r == nil {
		return nil
	}
	return &Fixes{r}
}

const FixesRequestDestroy uint32 = 0
const FixesRequestDestroyRegistry uint32 = 1
const FixesRequestAckGlobalRemove uint32 = 2

// FixesError wl_fixes error values.
type FixesError uint32

const (
	FixesErrorInvalidAckRemove FixesError = 0
)

// FixesHandler handles wl_fixes requests.
type FixesHandler interface {
	Destroy(self *Fixes)
	DestroyRegistry(self *Fixes, registry *Registry)
	AckGlobalRemove(self *Fixes, registry *Registry, name uint32)
}

func NewFixes(c server.Client, version int32, id uint32, h FixesHandler) (*Fixes, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for wl_fixes")
	}
	var self *Fixes
	r, err := c.CreateResource(FixesInterface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Destroy(self)
			self.Destroy()
		case 1:
			h.DestroyRegistry(self, WrapRegistry(args[0].Resource()))
		case 2:
			h.AckGlobalRemove(self, WrapRegistry(args[0].Resource()), args[1].Uint())
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapFixes(r)
	r.Data = self
	return self, nil
}
func NewFixesGlobal(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(FixesInterface, version, bind)
}
func resourceOf(v interface{ GetResource() *server.Resource }) *server.Resource {
	if v == nil {
		return nil
	}
	return v.GetResource()
}
func (self *Display) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *Registry) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *Callback) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *Compositor) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *ShmPool) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *Shm) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *Buffer) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *DataOffer) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *DataSource) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *DataDevice) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *DataDeviceManager) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *Shell) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *ShellSurface) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *Surface) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *Seat) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *Pointer) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *Keyboard) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *Touch) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *Output) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *Region) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *Subcompositor) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *Subsurface) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *Fixes) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
