// Code generated by wlgen; DO NOT EDIT.
package xdgsessionmanagement

import (
	"fmt"
	xdgshell "github.com/bnema/purego-libwayland/protocol/xdgshell"
	"github.com/bnema/purego-libwayland/server"
	"runtime"
)

var SessionManagerV1Interface *server.Interface
var SessionV1Interface *server.Interface
var ToplevelSessionV1Interface *server.Interface

func init() {
	SessionManagerV1Interface = &server.Interface{Name: "xdg_session_manager_v1", Version: 1}
	SessionV1Interface = &server.Interface{Name: "xdg_session_v1", Version: 1}
	ToplevelSessionV1Interface = &server.Interface{Name: "xdg_toplevel_session_v1", Version: 1}
	SessionManagerV1Interface.Requests = []server.Message{
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
		{Name: "get_session", Signature: "nu?s", Types: []*server.Interface{SessionV1Interface, nil, nil}},
	}
	SessionManagerV1Interface.Events = []server.Message{}
	SessionV1Interface.Requests = []server.Message{
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
		{Name: "remove", Signature: "", Types: []*server.Interface{}},
		{Name: "add_toplevel", Signature: "nos", Types: []*server.Interface{ToplevelSessionV1Interface, xdgshell.ToplevelInterface, nil}},
		{Name: "restore_toplevel", Signature: "nos", Types: []*server.Interface{ToplevelSessionV1Interface, xdgshell.ToplevelInterface, nil}},
		{Name: "remove_toplevel", Signature: "s", Types: []*server.Interface{nil}},
	}
	SessionV1Interface.Events = []server.Message{
		{Name: "created", Signature: "s", Types: []*server.Interface{nil}},
		{Name: "restored", Signature: "", Types: []*server.Interface{}},
		{Name: "replaced", Signature: "", Types: []*server.Interface{}},
	}
	ToplevelSessionV1Interface.Requests = []server.Message{
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
		{Name: "rename", Signature: "s", Types: []*server.Interface{nil}},
	}
	ToplevelSessionV1Interface.Events = []server.Message{
		{Name: "restored", Signature: "", Types: []*server.Interface{}},
	}
	if err := server.NewInterfaces(SessionManagerV1Interface, SessionV1Interface, ToplevelSessionV1Interface); err != nil {
		panic(err)
	}
}

// SessionManagerV1 manage sessions for applications.
type SessionManagerV1 struct{ *server.Resource }

func WrapSessionManagerV1(r *server.Resource) *SessionManagerV1 {
	if r == nil {
		return nil
	}
	return &SessionManagerV1{r}
}

const SessionManagerV1RequestDestroy uint32 = 0
const SessionManagerV1RequestGetSession uint32 = 1

// SessionManagerV1Error .
type SessionManagerV1Error uint32

const (
	SessionManagerV1ErrorInUse            SessionManagerV1Error = 1
	SessionManagerV1ErrorInvalidSessionId SessionManagerV1Error = 2
	SessionManagerV1ErrorInvalidReason    SessionManagerV1Error = 3
)

// SessionManagerV1Reason reason for getting a session.
type SessionManagerV1Reason uint32

const (
	SessionManagerV1ReasonLaunch         SessionManagerV1Reason = 1
	SessionManagerV1ReasonRecover        SessionManagerV1Reason = 2
	SessionManagerV1ReasonSessionRestore SessionManagerV1Reason = 3
)

// SessionManagerV1Handler handles xdg_session_manager_v1 requests.
type SessionManagerV1Handler interface {
	Destroy(self *SessionManagerV1)
	GetSession(self *SessionManagerV1, id uint32, reason uint32, sessionId string)
}

func NewSessionManagerV1(c server.Client, version int32, id uint32, h SessionManagerV1Handler) (*SessionManagerV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for xdg_session_manager_v1")
	}
	var self *SessionManagerV1
	r, err := c.CreateResource(SessionManagerV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Destroy(self)
			self.Destroy()
		case 1:
			h.GetSession(self, args[0].NewID(), args[1].Uint(), args[2].String())
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapSessionManagerV1(r)
	r.Data = self
	return self, nil
}
func NewSessionManagerV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(SessionManagerV1Interface, version, bind)
}

// SessionV1 A session for an application.
type SessionV1 struct{ *server.Resource }

func WrapSessionV1(r *server.Resource) *SessionV1 {
	if r == nil {
		return nil
	}
	return &SessionV1{r}
}

const SessionV1RequestDestroy uint32 = 0
const SessionV1RequestRemove uint32 = 1
const SessionV1RequestAddToplevel uint32 = 2
const SessionV1RequestRestoreToplevel uint32 = 3
const SessionV1RequestRemoveToplevel uint32 = 4
const SessionV1EventCreated uint32 = 0
const SessionV1EventRestored uint32 = 1
const SessionV1EventReplaced uint32 = 2

// SessionV1Error .
type SessionV1Error uint32

const (
	SessionV1ErrorNameInUse     SessionV1Error = 1
	SessionV1ErrorAlreadyMapped SessionV1Error = 2
	SessionV1ErrorInvalidName   SessionV1Error = 3
	SessionV1ErrorAlreadyAdded  SessionV1Error = 4
)

// SessionV1Handler handles xdg_session_v1 requests.
type SessionV1Handler interface {
	Destroy(self *SessionV1)
	Remove(self *SessionV1)
	AddToplevel(self *SessionV1, id uint32, toplevel *xdgshell.Toplevel, name string)
	RestoreToplevel(self *SessionV1, id uint32, toplevel *xdgshell.Toplevel, name string)
	RemoveToplevel(self *SessionV1, name string)
}

func NewSessionV1(c server.Client, version int32, id uint32, h SessionV1Handler) (*SessionV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for xdg_session_v1")
	}
	var self *SessionV1
	r, err := c.CreateResource(SessionV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Destroy(self)
			self.Destroy()
		case 1:
			h.Remove(self)
			self.Destroy()
		case 2:
			h.AddToplevel(self, args[0].NewID(), xdgshell.WrapToplevel(args[1].Resource()), args[2].String())
		case 3:
			h.RestoreToplevel(self, args[0].NewID(), xdgshell.WrapToplevel(args[1].Resource()), args[2].String())
		case 4:
			h.RemoveToplevel(self, args[0].String())
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapSessionV1(r)
	r.Data = self
	return self, nil
}

// SendCreated newly-created session id.
func (self *SessionV1) SendCreated(sessionId string) {
	var p runtime.Pinner
	defer p.Unpin()
	self.PostEvent(SessionV1EventCreated, server.String(&p, sessionId, false))
}

// SendRestored the session has been restored.
func (self *SessionV1) SendRestored() {
	self.PostEvent(SessionV1EventRestored)
}

// SendReplaced the session has been replaced.
func (self *SessionV1) SendReplaced() {
	self.PostEvent(SessionV1EventReplaced)
}
func NewSessionV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(SessionV1Interface, version, bind)
}

// ToplevelSessionV1 A session for an application.
type ToplevelSessionV1 struct{ *server.Resource }

func WrapToplevelSessionV1(r *server.Resource) *ToplevelSessionV1 {
	if r == nil {
		return nil
	}
	return &ToplevelSessionV1{r}
}

const ToplevelSessionV1RequestDestroy uint32 = 0
const ToplevelSessionV1RequestRename uint32 = 1
const ToplevelSessionV1EventRestored uint32 = 0

// ToplevelSessionV1Handler handles xdg_toplevel_session_v1 requests.
type ToplevelSessionV1Handler interface {
	Destroy(self *ToplevelSessionV1)
	Rename(self *ToplevelSessionV1, name string)
}

func NewToplevelSessionV1(c server.Client, version int32, id uint32, h ToplevelSessionV1Handler) (*ToplevelSessionV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for xdg_toplevel_session_v1")
	}
	var self *ToplevelSessionV1
	r, err := c.CreateResource(ToplevelSessionV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Destroy(self)
			self.Destroy()
		case 1:
			h.Rename(self, args[0].String())
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapToplevelSessionV1(r)
	r.Data = self
	return self, nil
}

// SendRestored a toplevel's session has been restored.
func (self *ToplevelSessionV1) SendRestored() {
	self.PostEvent(ToplevelSessionV1EventRestored)
}
func NewToplevelSessionV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(ToplevelSessionV1Interface, version, bind)
}
func resourceOf(v interface{ GetResource() *server.Resource }) *server.Resource {
	if v == nil {
		return nil
	}
	return v.GetResource()
}
func (self *SessionManagerV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *SessionV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *ToplevelSessionV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
