// Code generated by wlgen; DO NOT EDIT.
package exttransientseat

import (
	"fmt"
	"github.com/bnema/purego-libwayland/server"
)

var ExtTransientSeatManagerV1Interface *server.Interface
var ExtTransientSeatV1Interface *server.Interface

func init() {
	ExtTransientSeatManagerV1Interface = &server.Interface{Name: "ext_transient_seat_manager_v1", Version: 1}
	ExtTransientSeatV1Interface = &server.Interface{Name: "ext_transient_seat_v1", Version: 1}
	ExtTransientSeatManagerV1Interface.Requests = []server.Message{
		{Name: "create", Signature: "n", Types: []*server.Interface{ExtTransientSeatV1Interface}},
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
	}
	ExtTransientSeatManagerV1Interface.Events = []server.Message{}
	ExtTransientSeatV1Interface.Requests = []server.Message{
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
	}
	ExtTransientSeatV1Interface.Events = []server.Message{
		{Name: "ready", Signature: "u", Types: []*server.Interface{nil}},
		{Name: "denied", Signature: "", Types: []*server.Interface{}},
	}
	if err := server.NewInterfaces(ExtTransientSeatManagerV1Interface, ExtTransientSeatV1Interface); err != nil {
		panic(err)
	}
}

// ExtTransientSeatManagerV1 transient seat manager.
type ExtTransientSeatManagerV1 struct{ *server.Resource }

func WrapExtTransientSeatManagerV1(r *server.Resource) *ExtTransientSeatManagerV1 {
	if r == nil {
		return nil
	}
	return &ExtTransientSeatManagerV1{r}
}

const ExtTransientSeatManagerV1RequestCreate uint32 = 0
const ExtTransientSeatManagerV1RequestDestroy uint32 = 1

// ExtTransientSeatManagerV1Handler handles ext_transient_seat_manager_v1 requests.
type ExtTransientSeatManagerV1Handler interface {
	Create(self *ExtTransientSeatManagerV1, seat uint32)
	Destroy(self *ExtTransientSeatManagerV1)
}

func NewExtTransientSeatManagerV1(c server.Client, version int32, id uint32, h ExtTransientSeatManagerV1Handler) (*ExtTransientSeatManagerV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for ext_transient_seat_manager_v1")
	}
	var self *ExtTransientSeatManagerV1
	r, err := c.CreateResource(ExtTransientSeatManagerV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Create(self, args[0].NewID())
		case 1:
			h.Destroy(self)
			self.Destroy()
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapExtTransientSeatManagerV1(r)
	r.Data = self
	return self, nil
}
func NewExtTransientSeatManagerV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(ExtTransientSeatManagerV1Interface, version, bind)
}

// ExtTransientSeatV1 transient seat handle.
type ExtTransientSeatV1 struct{ *server.Resource }

func WrapExtTransientSeatV1(r *server.Resource) *ExtTransientSeatV1 {
	if r == nil {
		return nil
	}
	return &ExtTransientSeatV1{r}
}

const ExtTransientSeatV1RequestDestroy uint32 = 0
const ExtTransientSeatV1EventReady uint32 = 0
const ExtTransientSeatV1EventDenied uint32 = 1

// ExtTransientSeatV1Handler handles ext_transient_seat_v1 requests.
type ExtTransientSeatV1Handler interface {
	Destroy(self *ExtTransientSeatV1)
}

func NewExtTransientSeatV1(c server.Client, version int32, id uint32, h ExtTransientSeatV1Handler) (*ExtTransientSeatV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for ext_transient_seat_v1")
	}
	var self *ExtTransientSeatV1
	r, err := c.CreateResource(ExtTransientSeatV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Destroy(self)
			self.Destroy()
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapExtTransientSeatV1(r)
	r.Data = self
	return self, nil
}

// SendReady transient seat is ready.
func (self *ExtTransientSeatV1) SendReady(globalName uint32) {
	self.PostEvent(ExtTransientSeatV1EventReady, server.Uint(globalName))
}

// SendDenied transient seat creation denied.
func (self *ExtTransientSeatV1) SendDenied() {
	self.PostEvent(ExtTransientSeatV1EventDenied)
}
func NewExtTransientSeatV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(ExtTransientSeatV1Interface, version, bind)
}
func resourceOf(v interface{ GetResource() *server.Resource }) *server.Resource {
	if v == nil {
		return nil
	}
	return v.GetResource()
}
func (self *ExtTransientSeatManagerV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *ExtTransientSeatV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
