// Code generated by wlgen; DO NOT EDIT.
package xdgdialog

import (
	"fmt"
	xdgshell "github.com/bnema/purego-libwayland/protocol/xdgshell"
	"github.com/bnema/purego-libwayland/server"
)

var WmDialogV1Interface *server.Interface
var DialogV1Interface *server.Interface

func init() {
	WmDialogV1Interface = &server.Interface{Name: "xdg_wm_dialog_v1", Version: 1}
	DialogV1Interface = &server.Interface{Name: "xdg_dialog_v1", Version: 1}
	WmDialogV1Interface.Requests = []server.Message{
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
		{Name: "get_xdg_dialog", Signature: "no", Types: []*server.Interface{DialogV1Interface, xdgshell.ToplevelInterface}},
	}
	WmDialogV1Interface.Events = []server.Message{}
	DialogV1Interface.Requests = []server.Message{
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
		{Name: "set_modal", Signature: "", Types: []*server.Interface{}},
		{Name: "unset_modal", Signature: "", Types: []*server.Interface{}},
	}
	DialogV1Interface.Events = []server.Message{}
	if err := server.NewInterfaces(WmDialogV1Interface, DialogV1Interface); err != nil {
		panic(err)
	}
}

// WmDialogV1 create dialogs related to other toplevels.
type WmDialogV1 struct{ *server.Resource }

func WrapWmDialogV1(r *server.Resource) *WmDialogV1 {
	if r == nil {
		return nil
	}
	return &WmDialogV1{r}
}

const WmDialogV1RequestDestroy uint32 = 0
const WmDialogV1RequestGetXdgDialog uint32 = 1

// WmDialogV1Error .
type WmDialogV1Error uint32

const (
	WmDialogV1ErrorAlreadyUsed WmDialogV1Error = 0
)

// WmDialogV1Handler handles xdg_wm_dialog_v1 requests.
type WmDialogV1Handler interface {
	Destroy(self *WmDialogV1)
	GetXdgDialog(self *WmDialogV1, id uint32, toplevel *xdgshell.Toplevel)
}

func NewWmDialogV1(c server.Client, version int32, id uint32, h WmDialogV1Handler) (*WmDialogV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for xdg_wm_dialog_v1")
	}
	var self *WmDialogV1
	r, err := c.CreateResource(WmDialogV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Destroy(self)
			self.Destroy()
		case 1:
			h.GetXdgDialog(self, args[0].NewID(), xdgshell.WrapToplevel(args[1].Resource()))
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapWmDialogV1(r)
	r.Data = self
	return self, nil
}
func NewWmDialogV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(WmDialogV1Interface, version, bind)
}

// DialogV1 dialog object.
type DialogV1 struct{ *server.Resource }

func WrapDialogV1(r *server.Resource) *DialogV1 {
	if r == nil {
		return nil
	}
	return &DialogV1{r}
}

const DialogV1RequestDestroy uint32 = 0
const DialogV1RequestSetModal uint32 = 1
const DialogV1RequestUnsetModal uint32 = 2

// DialogV1Handler handles xdg_dialog_v1 requests.
type DialogV1Handler interface {
	Destroy(self *DialogV1)
	SetModal(self *DialogV1)
	UnsetModal(self *DialogV1)
}

func NewDialogV1(c server.Client, version int32, id uint32, h DialogV1Handler) (*DialogV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for xdg_dialog_v1")
	}
	var self *DialogV1
	r, err := c.CreateResource(DialogV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Destroy(self)
			self.Destroy()
		case 1:
			h.SetModal(self)
		case 2:
			h.UnsetModal(self)
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapDialogV1(r)
	r.Data = self
	return self, nil
}
func NewDialogV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(DialogV1Interface, version, bind)
}
func resourceOf(v interface{ GetResource() *server.Resource }) *server.Resource {
	if v == nil {
		return nil
	}
	return v.GetResource()
}
func (self *WmDialogV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *DialogV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
