// Code generated by wlgen; DO NOT EDIT.
package wlrforeigntoplevel

import (
	"fmt"
	wayland "github.com/bnema/purego-libwayland/protocol/wayland"
	"github.com/bnema/purego-libwayland/server"
	"runtime"
)

var ZwlrForeignToplevelManagerV1Interface *server.Interface
var ZwlrForeignToplevelHandleV1Interface *server.Interface

func init() {
	ZwlrForeignToplevelManagerV1Interface = &server.Interface{Name: "zwlr_foreign_toplevel_manager_v1", Version: 3}
	ZwlrForeignToplevelHandleV1Interface = &server.Interface{Name: "zwlr_foreign_toplevel_handle_v1", Version: 3}
	ZwlrForeignToplevelManagerV1Interface.Requests = []server.Message{
		{Name: "stop", Signature: "", Types: []*server.Interface{}},
	}
	ZwlrForeignToplevelManagerV1Interface.Events = []server.Message{
		{Name: "toplevel", Signature: "n", Types: []*server.Interface{ZwlrForeignToplevelHandleV1Interface}},
		{Name: "finished", Signature: "", Types: []*server.Interface{}},
	}
	ZwlrForeignToplevelHandleV1Interface.Requests = []server.Message{
		{Name: "set_maximized", Signature: "", Types: []*server.Interface{}},
		{Name: "unset_maximized", Signature: "", Types: []*server.Interface{}},
		{Name: "set_minimized", Signature: "", Types: []*server.Interface{}},
		{Name: "unset_minimized", Signature: "", Types: []*server.Interface{}},
		{Name: "activate", Signature: "o", Types: []*server.Interface{wayland.SeatInterface}},
		{Name: "close", Signature: "", Types: []*server.Interface{}},
		{Name: "set_rectangle", Signature: "oiiii", Types: []*server.Interface{wayland.SurfaceInterface, nil, nil, nil, nil}},
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
		{Name: "set_fullscreen", Signature: "2?o", Types: []*server.Interface{wayland.OutputInterface}},
		{Name: "unset_fullscreen", Signature: "2", Types: []*server.Interface{}},
	}
	ZwlrForeignToplevelHandleV1Interface.Events = []server.Message{
		{Name: "title", Signature: "s", Types: []*server.Interface{nil}},
		{Name: "app_id", Signature: "s", Types: []*server.Interface{nil}},
		{Name: "output_enter", Signature: "o", Types: []*server.Interface{wayland.OutputInterface}},
		{Name: "output_leave", Signature: "o", Types: []*server.Interface{wayland.OutputInterface}},
		{Name: "state", Signature: "a", Types: []*server.Interface{nil}},
		{Name: "done", Signature: "", Types: []*server.Interface{}},
		{Name: "closed", Signature: "", Types: []*server.Interface{}},
		{Name: "parent", Signature: "3?o", Types: []*server.Interface{ZwlrForeignToplevelHandleV1Interface}},
	}
	if err := server.NewInterfaces(ZwlrForeignToplevelManagerV1Interface, ZwlrForeignToplevelHandleV1Interface); err != nil {
		panic(err)
	}
}

// ZwlrForeignToplevelManagerV1 list and control opened apps.
type ZwlrForeignToplevelManagerV1 struct{ *server.Resource }

func WrapZwlrForeignToplevelManagerV1(r *server.Resource) *ZwlrForeignToplevelManagerV1 {
	if r == nil {
		return nil
	}
	return &ZwlrForeignToplevelManagerV1{r}
}

const ZwlrForeignToplevelManagerV1RequestStop uint32 = 0
const ZwlrForeignToplevelManagerV1EventToplevel uint32 = 0
const ZwlrForeignToplevelManagerV1EventFinished uint32 = 1

// ZwlrForeignToplevelManagerV1Handler handles zwlr_foreign_toplevel_manager_v1 requests.
type ZwlrForeignToplevelManagerV1Handler interface {
	Stop(self *ZwlrForeignToplevelManagerV1)
}

func NewZwlrForeignToplevelManagerV1(c server.Client, version int32, id uint32, h ZwlrForeignToplevelManagerV1Handler) (*ZwlrForeignToplevelManagerV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for zwlr_foreign_toplevel_manager_v1")
	}
	var self *ZwlrForeignToplevelManagerV1
	r, err := c.CreateResource(ZwlrForeignToplevelManagerV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Stop(self)
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapZwlrForeignToplevelManagerV1(r)
	r.Data = self
	return self, nil
}

// SendToplevel a toplevel has been created.
func (self *ZwlrForeignToplevelManagerV1) SendToplevel(toplevel *ZwlrForeignToplevelHandleV1) {
	self.PostEvent(ZwlrForeignToplevelManagerV1EventToplevel, server.NewID(resourceOf(toplevel)))
}

// SendFinished the compositor has finished with the toplevel manager.
func (self *ZwlrForeignToplevelManagerV1) SendFinished() {
	self.PostEvent(ZwlrForeignToplevelManagerV1EventFinished)
}
func NewZwlrForeignToplevelManagerV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(ZwlrForeignToplevelManagerV1Interface, version, bind)
}

// ZwlrForeignToplevelHandleV1 an opened toplevel.
type ZwlrForeignToplevelHandleV1 struct{ *server.Resource }

func WrapZwlrForeignToplevelHandleV1(r *server.Resource) *ZwlrForeignToplevelHandleV1 {
	if r == nil {
		return nil
	}
	return &ZwlrForeignToplevelHandleV1{r}
}

const ZwlrForeignToplevelHandleV1RequestSetMaximized uint32 = 0
const ZwlrForeignToplevelHandleV1RequestUnsetMaximized uint32 = 1
const ZwlrForeignToplevelHandleV1RequestSetMinimized uint32 = 2
const ZwlrForeignToplevelHandleV1RequestUnsetMinimized uint32 = 3
const ZwlrForeignToplevelHandleV1RequestActivate uint32 = 4
const ZwlrForeignToplevelHandleV1RequestClose uint32 = 5
const ZwlrForeignToplevelHandleV1RequestSetRectangle uint32 = 6
const ZwlrForeignToplevelHandleV1RequestDestroy uint32 = 7
const ZwlrForeignToplevelHandleV1RequestSetFullscreen uint32 = 8
const ZwlrForeignToplevelHandleV1RequestUnsetFullscreen uint32 = 9
const ZwlrForeignToplevelHandleV1EventTitle uint32 = 0
const ZwlrForeignToplevelHandleV1EventAppId uint32 = 1
const ZwlrForeignToplevelHandleV1EventOutputEnter uint32 = 2
const ZwlrForeignToplevelHandleV1EventOutputLeave uint32 = 3
const ZwlrForeignToplevelHandleV1EventState uint32 = 4
const ZwlrForeignToplevelHandleV1EventDone uint32 = 5
const ZwlrForeignToplevelHandleV1EventClosed uint32 = 6
const ZwlrForeignToplevelHandleV1EventParent uint32 = 7

// ZwlrForeignToplevelHandleV1State types of states on the toplevel.
type ZwlrForeignToplevelHandleV1State uint32

const (
	ZwlrForeignToplevelHandleV1StateMaximized  ZwlrForeignToplevelHandleV1State = 0
	ZwlrForeignToplevelHandleV1StateMinimized  ZwlrForeignToplevelHandleV1State = 1
	ZwlrForeignToplevelHandleV1StateActivated  ZwlrForeignToplevelHandleV1State = 2
	ZwlrForeignToplevelHandleV1StateFullscreen ZwlrForeignToplevelHandleV1State = 3
)

// ZwlrForeignToplevelHandleV1Error .
type ZwlrForeignToplevelHandleV1Error uint32

const (
	ZwlrForeignToplevelHandleV1ErrorInvalidRectangle ZwlrForeignToplevelHandleV1Error = 0
)

// ZwlrForeignToplevelHandleV1Handler handles zwlr_foreign_toplevel_handle_v1 requests.
type ZwlrForeignToplevelHandleV1Handler interface {
	SetMaximized(self *ZwlrForeignToplevelHandleV1)
	UnsetMaximized(self *ZwlrForeignToplevelHandleV1)
	SetMinimized(self *ZwlrForeignToplevelHandleV1)
	UnsetMinimized(self *ZwlrForeignToplevelHandleV1)
	Activate(self *ZwlrForeignToplevelHandleV1, seat *wayland.Seat)
	Close(self *ZwlrForeignToplevelHandleV1)
	SetRectangle(self *ZwlrForeignToplevelHandleV1, surface *wayland.Surface, x int32, y int32, width int32, height int32)
	Destroy(self *ZwlrForeignToplevelHandleV1)
	SetFullscreen(self *ZwlrForeignToplevelHandleV1, output *wayland.Output)
	UnsetFullscreen(self *ZwlrForeignToplevelHandleV1)
}

func NewZwlrForeignToplevelHandleV1(c server.Client, version int32, id uint32, h ZwlrForeignToplevelHandleV1Handler) (*ZwlrForeignToplevelHandleV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for zwlr_foreign_toplevel_handle_v1")
	}
	var self *ZwlrForeignToplevelHandleV1
	r, err := c.CreateResource(ZwlrForeignToplevelHandleV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.SetMaximized(self)
		case 1:
			h.UnsetMaximized(self)
		case 2:
			h.SetMinimized(self)
		case 3:
			h.UnsetMinimized(self)
		case 4:
			h.Activate(self, wayland.WrapSeat(args[0].Resource()))
		case 5:
			h.Close(self)
		case 6:
			h.SetRectangle(self, wayland.WrapSurface(args[0].Resource()), args[1].Int(), args[2].Int(), args[3].Int(), args[4].Int())
		case 7:
			h.Destroy(self)
			self.Destroy()
		case 8:
			h.SetFullscreen(self, wayland.WrapOutput(args[0].Resource()))
		case 9:
			h.UnsetFullscreen(self)
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapZwlrForeignToplevelHandleV1(r)
	r.Data = self
	return self, nil
}

// SendTitle title change.
func (self *ZwlrForeignToplevelHandleV1) SendTitle(title string) {
	var p runtime.Pinner
	defer p.Unpin()
	self.PostEvent(ZwlrForeignToplevelHandleV1EventTitle, server.String(&p, title, false))
}

// SendAppId app-id change.
func (self *ZwlrForeignToplevelHandleV1) SendAppId(appId string) {
	var p runtime.Pinner
	defer p.Unpin()
	self.PostEvent(ZwlrForeignToplevelHandleV1EventAppId, server.String(&p, appId, false))
}

// SendOutputEnter toplevel entered an output.
func (self *ZwlrForeignToplevelHandleV1) SendOutputEnter(output *wayland.Output) {
	self.PostEvent(ZwlrForeignToplevelHandleV1EventOutputEnter, server.Object(resourceOf(output)))
}

// SendOutputLeave toplevel left an output.
func (self *ZwlrForeignToplevelHandleV1) SendOutputLeave(output *wayland.Output) {
	self.PostEvent(ZwlrForeignToplevelHandleV1EventOutputLeave, server.Object(resourceOf(output)))
}

// SendState the toplevel state changed.
func (self *ZwlrForeignToplevelHandleV1) SendState(state []byte) {
	var p runtime.Pinner
	defer p.Unpin()
	self.PostEvent(ZwlrForeignToplevelHandleV1EventState, server.Array(&p, state))
}

// SendDone all information about the toplevel has been sent.
func (self *ZwlrForeignToplevelHandleV1) SendDone() {
	self.PostEvent(ZwlrForeignToplevelHandleV1EventDone)
}

// SendClosed this toplevel has been destroyed.
func (self *ZwlrForeignToplevelHandleV1) SendClosed() {
	self.PostEvent(ZwlrForeignToplevelHandleV1EventClosed)
}

// SendParent parent change (since version 3).
func (self *ZwlrForeignToplevelHandleV1) SendParent(parent *ZwlrForeignToplevelHandleV1) {
	self.PostEvent(ZwlrForeignToplevelHandleV1EventParent, server.Object(resourceOf(parent)))
}
func NewZwlrForeignToplevelHandleV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(ZwlrForeignToplevelHandleV1Interface, version, bind)
}
func resourceOf(v interface{ GetResource() *server.Resource }) *server.Resource {
	if v == nil {
		return nil
	}
	return v.GetResource()
}
func (self *ZwlrForeignToplevelManagerV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *ZwlrForeignToplevelHandleV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
