// Code generated by wlgen; DO NOT EDIT.
package kdedecoration

import (
	"fmt"
	wayland "github.com/bnema/purego-libwayland/protocol/wayland"
	"github.com/bnema/purego-libwayland/server"
)

var OrgKdeKwinServerDecorationManagerInterface *server.Interface
var OrgKdeKwinServerDecorationInterface *server.Interface

func init() {
	OrgKdeKwinServerDecorationManagerInterface = &server.Interface{Name: "org_kde_kwin_server_decoration_manager", Version: 1}
	OrgKdeKwinServerDecorationInterface = &server.Interface{Name: "org_kde_kwin_server_decoration", Version: 1}
	OrgKdeKwinServerDecorationManagerInterface.Requests = []server.Message{
		{Name: "create", Signature: "no", Types: []*server.Interface{OrgKdeKwinServerDecorationInterface, wayland.SurfaceInterface}},
	}
	OrgKdeKwinServerDecorationManagerInterface.Events = []server.Message{
		{Name: "default_mode", Signature: "u", Types: []*server.Interface{nil}},
	}
	OrgKdeKwinServerDecorationInterface.Requests = []server.Message{
		{Name: "release", Signature: "", Types: []*server.Interface{}},
		{Name: "request_mode", Signature: "u", Types: []*server.Interface{nil}},
	}
	OrgKdeKwinServerDecorationInterface.Events = []server.Message{
		{Name: "mode", Signature: "u", Types: []*server.Interface{nil}},
	}
	if err := server.NewInterfaces(OrgKdeKwinServerDecorationManagerInterface, OrgKdeKwinServerDecorationInterface); err != nil {
		panic(err)
	}
}

// OrgKdeKwinServerDecorationManager Server side window decoration manager.
type OrgKdeKwinServerDecorationManager struct{ *server.Resource }

func WrapOrgKdeKwinServerDecorationManager(r *server.Resource) *OrgKdeKwinServerDecorationManager {
	if r == nil {
		return nil
	}
	return &OrgKdeKwinServerDecorationManager{r}
}

const OrgKdeKwinServerDecorationManagerRequestCreate uint32 = 0
const OrgKdeKwinServerDecorationManagerEventDefaultMode uint32 = 0

// OrgKdeKwinServerDecorationManagerMode Possible values to use in request_mode and the event mode..
type OrgKdeKwinServerDecorationManagerMode uint32

const (
	OrgKdeKwinServerDecorationManagerModeNone   OrgKdeKwinServerDecorationManagerMode = 0
	OrgKdeKwinServerDecorationManagerModeClient OrgKdeKwinServerDecorationManagerMode = 1
	OrgKdeKwinServerDecorationManagerModeServer OrgKdeKwinServerDecorationManagerMode = 2
)

// OrgKdeKwinServerDecorationManagerHandler handles org_kde_kwin_server_decoration_manager requests.
type OrgKdeKwinServerDecorationManagerHandler interface {
	Create(self *OrgKdeKwinServerDecorationManager, id uint32, surface *wayland.Surface)
}

func NewOrgKdeKwinServerDecorationManager(c server.Client, version int32, id uint32, h OrgKdeKwinServerDecorationManagerHandler) (*OrgKdeKwinServerDecorationManager, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for org_kde_kwin_server_decoration_manager")
	}
	var self *OrgKdeKwinServerDecorationManager
	r, err := c.CreateResource(OrgKdeKwinServerDecorationManagerInterface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Create(self, args[0].NewID(), wayland.WrapSurface(args[1].Resource()))
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapOrgKdeKwinServerDecorationManager(r)
	r.Data = self
	return self, nil
}

// SendDefaultMode The default mode used on the server.
func (self *OrgKdeKwinServerDecorationManager) SendDefaultMode(mode uint32) {
	self.PostEvent(OrgKdeKwinServerDecorationManagerEventDefaultMode, server.Uint(mode))
}
func NewOrgKdeKwinServerDecorationManagerGlobal(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(OrgKdeKwinServerDecorationManagerInterface, version, bind)
}

// OrgKdeKwinServerDecoration .
type OrgKdeKwinServerDecoration struct{ *server.Resource }

func WrapOrgKdeKwinServerDecoration(r *server.Resource) *OrgKdeKwinServerDecoration {
	if r == nil {
		return nil
	}
	return &OrgKdeKwinServerDecoration{r}
}

const OrgKdeKwinServerDecorationRequestRelease uint32 = 0
const OrgKdeKwinServerDecorationRequestRequestMode uint32 = 1
const OrgKdeKwinServerDecorationEventMode uint32 = 0

// OrgKdeKwinServerDecorationMode Possible values to use in request_mode and the event mode..
type OrgKdeKwinServerDecorationMode uint32

const (
	OrgKdeKwinServerDecorationModeNone   OrgKdeKwinServerDecorationMode = 0
	OrgKdeKwinServerDecorationModeClient OrgKdeKwinServerDecorationMode = 1
	OrgKdeKwinServerDecorationModeServer OrgKdeKwinServerDecorationMode = 2
)

// OrgKdeKwinServerDecorationHandler handles org_kde_kwin_server_decoration requests.
type OrgKdeKwinServerDecorationHandler interface {
	Release(self *OrgKdeKwinServerDecoration)
	RequestMode(self *OrgKdeKwinServerDecoration, mode uint32)
}

func NewOrgKdeKwinServerDecoration(c server.Client, version int32, id uint32, h OrgKdeKwinServerDecorationHandler) (*OrgKdeKwinServerDecoration, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for org_kde_kwin_server_decoration")
	}
	var self *OrgKdeKwinServerDecoration
	r, err := c.CreateResource(OrgKdeKwinServerDecorationInterface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Release(self)
			self.Destroy()
		case 1:
			h.RequestMode(self, args[0].Uint())
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapOrgKdeKwinServerDecoration(r)
	r.Data = self
	return self, nil
}

// SendMode The new decoration mode applied by the server.
func (self *OrgKdeKwinServerDecoration) SendMode(mode uint32) {
	self.PostEvent(OrgKdeKwinServerDecorationEventMode, server.Uint(mode))
}
func NewOrgKdeKwinServerDecorationGlobal(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(OrgKdeKwinServerDecorationInterface, version, bind)
}
func resourceOf(v interface{ GetResource() *server.Resource }) *server.Resource {
	if v == nil {
		return nil
	}
	return v.GetResource()
}
func (self *OrgKdeKwinServerDecorationManager) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *OrgKdeKwinServerDecoration) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
