// Code generated by wlgen; DO NOT EDIT.
package xdgdecoration

import (
	"fmt"
	xdgshell "github.com/bnema/purego-libwayland/protocol/xdgshell"
	"github.com/bnema/purego-libwayland/server"
)

var ZxdgDecorationManagerV1Interface *server.Interface
var ZxdgToplevelDecorationV1Interface *server.Interface

func init() {
	ZxdgDecorationManagerV1Interface = &server.Interface{Name: "zxdg_decoration_manager_v1", Version: 2}
	ZxdgToplevelDecorationV1Interface = &server.Interface{Name: "zxdg_toplevel_decoration_v1", Version: 2}
	ZxdgDecorationManagerV1Interface.Requests = []server.Message{
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
		{Name: "get_toplevel_decoration", Signature: "no", Types: []*server.Interface{ZxdgToplevelDecorationV1Interface, xdgshell.ToplevelInterface}},
	}
	ZxdgDecorationManagerV1Interface.Events = []server.Message{}
	ZxdgToplevelDecorationV1Interface.Requests = []server.Message{
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
		{Name: "set_mode", Signature: "u", Types: []*server.Interface{nil}},
		{Name: "unset_mode", Signature: "", Types: []*server.Interface{}},
	}
	ZxdgToplevelDecorationV1Interface.Events = []server.Message{
		{Name: "configure", Signature: "u", Types: []*server.Interface{nil}},
	}
	if err := server.NewInterfaces(ZxdgDecorationManagerV1Interface, ZxdgToplevelDecorationV1Interface); err != nil {
		panic(err)
	}
}

// ZxdgDecorationManagerV1 window decoration manager.
type ZxdgDecorationManagerV1 struct{ *server.Resource }

func WrapZxdgDecorationManagerV1(r *server.Resource) *ZxdgDecorationManagerV1 {
	if r == nil {
		return nil
	}
	return &ZxdgDecorationManagerV1{r}
}

const ZxdgDecorationManagerV1RequestDestroy uint32 = 0
const ZxdgDecorationManagerV1RequestGetToplevelDecoration uint32 = 1

// ZxdgDecorationManagerV1Handler handles zxdg_decoration_manager_v1 requests.
type ZxdgDecorationManagerV1Handler interface {
	Destroy(self *ZxdgDecorationManagerV1)
	GetToplevelDecoration(self *ZxdgDecorationManagerV1, id uint32, toplevel *xdgshell.Toplevel)
}

func NewZxdgDecorationManagerV1(c server.Client, version int32, id uint32, h ZxdgDecorationManagerV1Handler) (*ZxdgDecorationManagerV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for zxdg_decoration_manager_v1")
	}
	var self *ZxdgDecorationManagerV1
	r, err := c.CreateResource(ZxdgDecorationManagerV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Destroy(self)
			self.Destroy()
		case 1:
			h.GetToplevelDecoration(self, args[0].NewID(), xdgshell.WrapToplevel(args[1].Resource()))
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapZxdgDecorationManagerV1(r)
	r.Data = self
	return self, nil
}
func NewZxdgDecorationManagerV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(ZxdgDecorationManagerV1Interface, version, bind)
}

// ZxdgToplevelDecorationV1 decoration object for a toplevel surface.
type ZxdgToplevelDecorationV1 struct{ *server.Resource }

func WrapZxdgToplevelDecorationV1(r *server.Resource) *ZxdgToplevelDecorationV1 {
	if r == nil {
		return nil
	}
	return &ZxdgToplevelDecorationV1{r}
}

const ZxdgToplevelDecorationV1RequestDestroy uint32 = 0
const ZxdgToplevelDecorationV1RequestSetMode uint32 = 1
const ZxdgToplevelDecorationV1RequestUnsetMode uint32 = 2
const ZxdgToplevelDecorationV1EventConfigure uint32 = 0

// ZxdgToplevelDecorationV1Error .
type ZxdgToplevelDecorationV1Error uint32

const (
	ZxdgToplevelDecorationV1ErrorUnconfiguredBuffer ZxdgToplevelDecorationV1Error = 0
	ZxdgToplevelDecorationV1ErrorAlreadyConstructed ZxdgToplevelDecorationV1Error = 1
	ZxdgToplevelDecorationV1ErrorOrphaned           ZxdgToplevelDecorationV1Error = 2
	ZxdgToplevelDecorationV1ErrorInvalidMode        ZxdgToplevelDecorationV1Error = 3
)

// ZxdgToplevelDecorationV1Mode window decoration modes.
type ZxdgToplevelDecorationV1Mode uint32

const (
	ZxdgToplevelDecorationV1ModeClientSide ZxdgToplevelDecorationV1Mode = 1
	ZxdgToplevelDecorationV1ModeServerSide ZxdgToplevelDecorationV1Mode = 2
)

// ZxdgToplevelDecorationV1Handler handles zxdg_toplevel_decoration_v1 requests.
type ZxdgToplevelDecorationV1Handler interface {
	Destroy(self *ZxdgToplevelDecorationV1)
	SetMode(self *ZxdgToplevelDecorationV1, mode uint32)
	UnsetMode(self *ZxdgToplevelDecorationV1)
}

func NewZxdgToplevelDecorationV1(c server.Client, version int32, id uint32, h ZxdgToplevelDecorationV1Handler) (*ZxdgToplevelDecorationV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for zxdg_toplevel_decoration_v1")
	}
	var self *ZxdgToplevelDecorationV1
	r, err := c.CreateResource(ZxdgToplevelDecorationV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Destroy(self)
			self.Destroy()
		case 1:
			h.SetMode(self, args[0].Uint())
		case 2:
			h.UnsetMode(self)
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapZxdgToplevelDecorationV1(r)
	r.Data = self
	return self, nil
}

// SendConfigure notify a decoration mode change.
func (self *ZxdgToplevelDecorationV1) SendConfigure(mode uint32) {
	self.PostEvent(ZxdgToplevelDecorationV1EventConfigure, server.Uint(mode))
}
func NewZxdgToplevelDecorationV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(ZxdgToplevelDecorationV1Interface, version, bind)
}
func resourceOf(v interface{ GetResource() *server.Resource }) *server.Resource {
	if v == nil {
		return nil
	}
	return v.GetResource()
}
func (self *ZxdgDecorationManagerV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *ZxdgToplevelDecorationV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
