// Code generated by wlgen; DO NOT EDIT.
package wlroutputmanagement

import (
	"fmt"
	"github.com/bnema/purego-libwayland/server"
	"runtime"
)

var ZwlrOutputManagerV1Interface *server.Interface
var ZwlrOutputHeadV1Interface *server.Interface
var ZwlrOutputModeV1Interface *server.Interface
var ZwlrOutputConfigurationV1Interface *server.Interface
var ZwlrOutputConfigurationHeadV1Interface *server.Interface

func init() {
	ZwlrOutputManagerV1Interface = &server.Interface{Name: "zwlr_output_manager_v1", Version: 4}
	ZwlrOutputHeadV1Interface = &server.Interface{Name: "zwlr_output_head_v1", Version: 4}
	ZwlrOutputModeV1Interface = &server.Interface{Name: "zwlr_output_mode_v1", Version: 3}
	ZwlrOutputConfigurationV1Interface = &server.Interface{Name: "zwlr_output_configuration_v1", Version: 4}
	ZwlrOutputConfigurationHeadV1Interface = &server.Interface{Name: "zwlr_output_configuration_head_v1", Version: 4}
	ZwlrOutputManagerV1Interface.Requests = []server.Message{
		{Name: "create_configuration", Signature: "nu", Types: []*server.Interface{ZwlrOutputConfigurationV1Interface, nil}},
		{Name: "stop", Signature: "", Types: []*server.Interface{}},
	}
	ZwlrOutputManagerV1Interface.Events = []server.Message{
		{Name: "head", Signature: "n", Types: []*server.Interface{ZwlrOutputHeadV1Interface}},
		{Name: "done", Signature: "u", Types: []*server.Interface{nil}},
		{Name: "finished", Signature: "", Types: []*server.Interface{}},
	}
	ZwlrOutputHeadV1Interface.Requests = []server.Message{
		{Name: "release", Signature: "3", Types: []*server.Interface{}},
	}
	ZwlrOutputHeadV1Interface.Events = []server.Message{
		{Name: "name", Signature: "s", Types: []*server.Interface{nil}},
		{Name: "description", Signature: "s", Types: []*server.Interface{nil}},
		{Name: "physical_size", Signature: "ii", Types: []*server.Interface{nil, nil}},
		{Name: "mode", Signature: "n", Types: []*server.Interface{ZwlrOutputModeV1Interface}},
		{Name: "enabled", Signature: "i", Types: []*server.Interface{nil}},
		{Name: "current_mode", Signature: "o", Types: []*server.Interface{ZwlrOutputModeV1Interface}},
		{Name: "position", Signature: "ii", Types: []*server.Interface{nil, nil}},
		{Name: "transform", Signature: "i", Types: []*server.Interface{nil}},
		{Name: "scale", Signature: "f", Types: []*server.Interface{nil}},
		{Name: "finished", Signature: "", Types: []*server.Interface{}},
		{Name: "make", Signature: "2s", Types: []*server.Interface{nil}},
		{Name: "model", Signature: "2s", Types: []*server.Interface{nil}},
		{Name: "serial_number", Signature: "2s", Types: []*server.Interface{nil}},
		{Name: "adaptive_sync", Signature: "4u", Types: []*server.Interface{nil}},
	}
	ZwlrOutputModeV1Interface.Requests = []server.Message{
		{Name: "release", Signature: "3", Types: []*server.Interface{}},
	}
	ZwlrOutputModeV1Interface.Events = []server.Message{
		{Name: "size", Signature: "ii", Types: []*server.Interface{nil, nil}},
		{Name: "refresh", Signature: "i", Types: []*server.Interface{nil}},
		{Name: "preferred", Signature: "", Types: []*server.Interface{}},
		{Name: "finished", Signature: "", Types: []*server.Interface{}},
	}
	ZwlrOutputConfigurationV1Interface.Requests = []server.Message{
		{Name: "enable_head", Signature: "no", Types: []*server.Interface{ZwlrOutputConfigurationHeadV1Interface, ZwlrOutputHeadV1Interface}},
		{Name: "disable_head", Signature: "o", Types: []*server.Interface{ZwlrOutputHeadV1Interface}},
		{Name: "apply", Signature: "", Types: []*server.Interface{}},
		{Name: "test", Signature: "", Types: []*server.Interface{}},
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
	}
	ZwlrOutputConfigurationV1Interface.Events = []server.Message{
		{Name: "succeeded", Signature: "", Types: []*server.Interface{}},
		{Name: "failed", Signature: "", Types: []*server.Interface{}},
		{Name: "cancelled", Signature: "", Types: []*server.Interface{}},
	}
	ZwlrOutputConfigurationHeadV1Interface.Requests = []server.Message{
		{Name: "set_mode", Signature: "o", Types: []*server.Interface{ZwlrOutputModeV1Interface}},
		{Name: "set_custom_mode", Signature: "iii", Types: []*server.Interface{nil, nil, nil}},
		{Name: "set_position", Signature: "ii", Types: []*server.Interface{nil, nil}},
		{Name: "set_transform", Signature: "i", Types: []*server.Interface{nil}},
		{Name: "set_scale", Signature: "f", Types: []*server.Interface{nil}},
		{Name: "set_adaptive_sync", Signature: "4u", Types: []*server.Interface{nil}},
	}
	ZwlrOutputConfigurationHeadV1Interface.Events = []server.Message{}
	if err := server.NewInterfaces(ZwlrOutputManagerV1Interface, ZwlrOutputHeadV1Interface, ZwlrOutputModeV1Interface, ZwlrOutputConfigurationV1Interface, ZwlrOutputConfigurationHeadV1Interface); err != nil {
		panic(err)
	}
}

// ZwlrOutputManagerV1 output device configuration manager.
type ZwlrOutputManagerV1 struct{ *server.Resource }

func WrapZwlrOutputManagerV1(r *server.Resource) *ZwlrOutputManagerV1 {
	if r == nil {
		return nil
	}
	return &ZwlrOutputManagerV1{r}
}

const ZwlrOutputManagerV1RequestCreateConfiguration uint32 = 0
const ZwlrOutputManagerV1RequestStop uint32 = 1
const ZwlrOutputManagerV1EventHead uint32 = 0
const ZwlrOutputManagerV1EventDone uint32 = 1
const ZwlrOutputManagerV1EventFinished uint32 = 2

// ZwlrOutputManagerV1Handler handles zwlr_output_manager_v1 requests.
type ZwlrOutputManagerV1Handler interface {
	CreateConfiguration(self *ZwlrOutputManagerV1, id uint32, serial uint32)
	Stop(self *ZwlrOutputManagerV1)
}

func NewZwlrOutputManagerV1(c server.Client, version int32, id uint32, h ZwlrOutputManagerV1Handler) (*ZwlrOutputManagerV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for zwlr_output_manager_v1")
	}
	var self *ZwlrOutputManagerV1
	r, err := c.CreateResource(ZwlrOutputManagerV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.CreateConfiguration(self, args[0].NewID(), args[1].Uint())
		case 1:
			h.Stop(self)
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapZwlrOutputManagerV1(r)
	r.Data = self
	return self, nil
}

// SendHead introduce a new head.
func (self *ZwlrOutputManagerV1) SendHead(head *ZwlrOutputHeadV1) {
	self.PostEvent(ZwlrOutputManagerV1EventHead, server.NewID(resourceOf(head)))
}

// SendDone sent all information about current configuration.
func (self *ZwlrOutputManagerV1) SendDone(serial uint32) {
	self.PostEvent(ZwlrOutputManagerV1EventDone, server.Uint(serial))
}

// SendFinished the compositor has finished with the manager.
func (self *ZwlrOutputManagerV1) SendFinished() {
	self.PostEvent(ZwlrOutputManagerV1EventFinished)
}
func NewZwlrOutputManagerV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(ZwlrOutputManagerV1Interface, version, bind)
}

// ZwlrOutputHeadV1 output device.
type ZwlrOutputHeadV1 struct{ *server.Resource }

func WrapZwlrOutputHeadV1(r *server.Resource) *ZwlrOutputHeadV1 {
	if r == nil {
		return nil
	}
	return &ZwlrOutputHeadV1{r}
}

const ZwlrOutputHeadV1RequestRelease uint32 = 0
const ZwlrOutputHeadV1EventName uint32 = 0
const ZwlrOutputHeadV1EventDescription uint32 = 1
const ZwlrOutputHeadV1EventPhysicalSize uint32 = 2
const ZwlrOutputHeadV1EventMode uint32 = 3
const ZwlrOutputHeadV1EventEnabled uint32 = 4
const ZwlrOutputHeadV1EventCurrentMode uint32 = 5
const ZwlrOutputHeadV1EventPosition uint32 = 6
const ZwlrOutputHeadV1EventTransform uint32 = 7
const ZwlrOutputHeadV1EventScale uint32 = 8
const ZwlrOutputHeadV1EventFinished uint32 = 9
const ZwlrOutputHeadV1EventMake uint32 = 10
const ZwlrOutputHeadV1EventModel uint32 = 11
const ZwlrOutputHeadV1EventSerialNumber uint32 = 12
const ZwlrOutputHeadV1EventAdaptiveSync uint32 = 13

// ZwlrOutputHeadV1AdaptiveSyncState .
type ZwlrOutputHeadV1AdaptiveSyncState uint32

const (
	ZwlrOutputHeadV1AdaptiveSyncStateDisabled ZwlrOutputHeadV1AdaptiveSyncState = 0
	ZwlrOutputHeadV1AdaptiveSyncStateEnabled  ZwlrOutputHeadV1AdaptiveSyncState = 1
)

// ZwlrOutputHeadV1Handler handles zwlr_output_head_v1 requests.
type ZwlrOutputHeadV1Handler interface {
	Release(self *ZwlrOutputHeadV1)
}

func NewZwlrOutputHeadV1(c server.Client, version int32, id uint32, h ZwlrOutputHeadV1Handler) (*ZwlrOutputHeadV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for zwlr_output_head_v1")
	}
	var self *ZwlrOutputHeadV1
	r, err := c.CreateResource(ZwlrOutputHeadV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Release(self)
			self.Destroy()
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapZwlrOutputHeadV1(r)
	r.Data = self
	return self, nil
}

// SendName head name.
func (self *ZwlrOutputHeadV1) SendName(name string) {
	var p runtime.Pinner
	defer p.Unpin()
	self.PostEvent(ZwlrOutputHeadV1EventName, server.String(&p, name, false))
}

// SendDescription head description.
func (self *ZwlrOutputHeadV1) SendDescription(description string) {
	var p runtime.Pinner
	defer p.Unpin()
	self.PostEvent(ZwlrOutputHeadV1EventDescription, server.String(&p, description, false))
}

// SendPhysicalSize head physical size.
func (self *ZwlrOutputHeadV1) SendPhysicalSize(width int32, height int32) {
	self.PostEvent(ZwlrOutputHeadV1EventPhysicalSize, server.Int(width), server.Int(height))
}

// SendMode introduce a mode.
func (self *ZwlrOutputHeadV1) SendMode(mode *ZwlrOutputModeV1) {
	self.PostEvent(ZwlrOutputHeadV1EventMode, server.NewID(resourceOf(mode)))
}

// SendEnabled head is enabled or disabled.
func (self *ZwlrOutputHeadV1) SendEnabled(enabled int32) {
	self.PostEvent(ZwlrOutputHeadV1EventEnabled, server.Int(enabled))
}

// SendCurrentMode current mode.
func (self *ZwlrOutputHeadV1) SendCurrentMode(mode *ZwlrOutputModeV1) {
	self.PostEvent(ZwlrOutputHeadV1EventCurrentMode, server.Object(resourceOf(mode)))
}

// SendPosition current position.
func (self *ZwlrOutputHeadV1) SendPosition(x int32, y int32) {
	self.PostEvent(ZwlrOutputHeadV1EventPosition, server.Int(x), server.Int(y))
}

// SendTransform current transformation.
func (self *ZwlrOutputHeadV1) SendTransform(transform int32) {
	self.PostEvent(ZwlrOutputHeadV1EventTransform, server.Int(transform))
}

// SendScale current scale.
func (self *ZwlrOutputHeadV1) SendScale(scale server.Fixed) {
	self.PostEvent(ZwlrOutputHeadV1EventScale, server.FixedArg(scale))
}

// SendFinished the head has disappeared.
func (self *ZwlrOutputHeadV1) SendFinished() {
	self.PostEvent(ZwlrOutputHeadV1EventFinished)
}

// SendMake head manufacturer (since version 2).
func (self *ZwlrOutputHeadV1) SendMake(make string) {
	var p runtime.Pinner
	defer p.Unpin()
	self.PostEvent(ZwlrOutputHeadV1EventMake, server.String(&p, make, false))
}

// SendModel head model (since version 2).
func (self *ZwlrOutputHeadV1) SendModel(model string) {
	var p runtime.Pinner
	defer p.Unpin()
	self.PostEvent(ZwlrOutputHeadV1EventModel, server.String(&p, model, false))
}

// SendSerialNumber head serial number (since version 2).
func (self *ZwlrOutputHeadV1) SendSerialNumber(serialNumber string) {
	var p runtime.Pinner
	defer p.Unpin()
	self.PostEvent(ZwlrOutputHeadV1EventSerialNumber, server.String(&p, serialNumber, false))
}

// SendAdaptiveSync current adaptive sync state (since version 4).
func (self *ZwlrOutputHeadV1) SendAdaptiveSync(state uint32) {
	self.PostEvent(ZwlrOutputHeadV1EventAdaptiveSync, server.Uint(state))
}
func NewZwlrOutputHeadV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(ZwlrOutputHeadV1Interface, version, bind)
}

// ZwlrOutputModeV1 output mode.
type ZwlrOutputModeV1 struct{ *server.Resource }

func WrapZwlrOutputModeV1(r *server.Resource) *ZwlrOutputModeV1 {
	if r == nil {
		return nil
	}
	return &ZwlrOutputModeV1{r}
}

const ZwlrOutputModeV1RequestRelease uint32 = 0
const ZwlrOutputModeV1EventSize uint32 = 0
const ZwlrOutputModeV1EventRefresh uint32 = 1
const ZwlrOutputModeV1EventPreferred uint32 = 2
const ZwlrOutputModeV1EventFinished uint32 = 3

// ZwlrOutputModeV1Handler handles zwlr_output_mode_v1 requests.
type ZwlrOutputModeV1Handler interface {
	Release(self *ZwlrOutputModeV1)
}

func NewZwlrOutputModeV1(c server.Client, version int32, id uint32, h ZwlrOutputModeV1Handler) (*ZwlrOutputModeV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for zwlr_output_mode_v1")
	}
	var self *ZwlrOutputModeV1
	r, err := c.CreateResource(ZwlrOutputModeV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Release(self)
			self.Destroy()
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapZwlrOutputModeV1(r)
	r.Data = self
	return self, nil
}

// SendSize mode size.
func (self *ZwlrOutputModeV1) SendSize(width int32, height int32) {
	self.PostEvent(ZwlrOutputModeV1EventSize, server.Int(width), server.Int(height))
}

// SendRefresh mode refresh rate.
func (self *ZwlrOutputModeV1) SendRefresh(refresh int32) {
	self.PostEvent(ZwlrOutputModeV1EventRefresh, server.Int(refresh))
}

// SendPreferred mode is preferred.
func (self *ZwlrOutputModeV1) SendPreferred() {
	self.PostEvent(ZwlrOutputModeV1EventPreferred)
}

// SendFinished the mode has disappeared.
func (self *ZwlrOutputModeV1) SendFinished() {
	self.PostEvent(ZwlrOutputModeV1EventFinished)
}
func NewZwlrOutputModeV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(ZwlrOutputModeV1Interface, version, bind)
}

// ZwlrOutputConfigurationV1 output configuration.
type ZwlrOutputConfigurationV1 struct{ *server.Resource }

func WrapZwlrOutputConfigurationV1(r *server.Resource) *ZwlrOutputConfigurationV1 {
	if r == nil {
		return nil
	}
	return &ZwlrOutputConfigurationV1{r}
}

const ZwlrOutputConfigurationV1RequestEnableHead uint32 = 0
const ZwlrOutputConfigurationV1RequestDisableHead uint32 = 1
const ZwlrOutputConfigurationV1RequestApply uint32 = 2
const ZwlrOutputConfigurationV1RequestTest uint32 = 3
const ZwlrOutputConfigurationV1RequestDestroy uint32 = 4
const ZwlrOutputConfigurationV1EventSucceeded uint32 = 0
const ZwlrOutputConfigurationV1EventFailed uint32 = 1
const ZwlrOutputConfigurationV1EventCancelled uint32 = 2

// ZwlrOutputConfigurationV1Error .
type ZwlrOutputConfigurationV1Error uint32

const (
	ZwlrOutputConfigurationV1ErrorAlreadyConfiguredHead ZwlrOutputConfigurationV1Error = 1
	ZwlrOutputConfigurationV1ErrorUnconfiguredHead      ZwlrOutputConfigurationV1Error = 2
	ZwlrOutputConfigurationV1ErrorAlreadyUsed           ZwlrOutputConfigurationV1Error = 3
)

// ZwlrOutputConfigurationV1Handler handles zwlr_output_configuration_v1 requests.
type ZwlrOutputConfigurationV1Handler interface {
	EnableHead(self *ZwlrOutputConfigurationV1, id uint32, head *ZwlrOutputHeadV1)
	DisableHead(self *ZwlrOutputConfigurationV1, head *ZwlrOutputHeadV1)
	Apply(self *ZwlrOutputConfigurationV1)
	Test(self *ZwlrOutputConfigurationV1)
	Destroy(self *ZwlrOutputConfigurationV1)
}

func NewZwlrOutputConfigurationV1(c server.Client, version int32, id uint32, h ZwlrOutputConfigurationV1Handler) (*ZwlrOutputConfigurationV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for zwlr_output_configuration_v1")
	}
	var self *ZwlrOutputConfigurationV1
	r, err := c.CreateResource(ZwlrOutputConfigurationV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.EnableHead(self, args[0].NewID(), WrapZwlrOutputHeadV1(args[1].Resource()))
		case 1:
			h.DisableHead(self, WrapZwlrOutputHeadV1(args[0].Resource()))
		case 2:
			h.Apply(self)
		case 3:
			h.Test(self)
		case 4:
			h.Destroy(self)
			self.Destroy()
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapZwlrOutputConfigurationV1(r)
	r.Data = self
	return self, nil
}

// SendSucceeded configuration changes succeeded.
func (self *ZwlrOutputConfigurationV1) SendSucceeded() {
	self.PostEvent(ZwlrOutputConfigurationV1EventSucceeded)
}

// SendFailed configuration changes failed.
func (self *ZwlrOutputConfigurationV1) SendFailed() {
	self.PostEvent(ZwlrOutputConfigurationV1EventFailed)
}

// SendCancelled configuration has been cancelled.
func (self *ZwlrOutputConfigurationV1) SendCancelled() {
	self.PostEvent(ZwlrOutputConfigurationV1EventCancelled)
}
func NewZwlrOutputConfigurationV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(ZwlrOutputConfigurationV1Interface, version, bind)
}

// ZwlrOutputConfigurationHeadV1 head configuration.
type ZwlrOutputConfigurationHeadV1 struct{ *server.Resource }

func WrapZwlrOutputConfigurationHeadV1(r *server.Resource) *ZwlrOutputConfigurationHeadV1 {
	if r == nil {
		return nil
	}
	return &ZwlrOutputConfigurationHeadV1{r}
}

const ZwlrOutputConfigurationHeadV1RequestSetMode uint32 = 0
const ZwlrOutputConfigurationHeadV1RequestSetCustomMode uint32 = 1
const ZwlrOutputConfigurationHeadV1RequestSetPosition uint32 = 2
const ZwlrOutputConfigurationHeadV1RequestSetTransform uint32 = 3
const ZwlrOutputConfigurationHeadV1RequestSetScale uint32 = 4
const ZwlrOutputConfigurationHeadV1RequestSetAdaptiveSync uint32 = 5

// ZwlrOutputConfigurationHeadV1Error .
type ZwlrOutputConfigurationHeadV1Error uint32

const (
	ZwlrOutputConfigurationHeadV1ErrorAlreadySet               ZwlrOutputConfigurationHeadV1Error = 1
	ZwlrOutputConfigurationHeadV1ErrorInvalidMode              ZwlrOutputConfigurationHeadV1Error = 2
	ZwlrOutputConfigurationHeadV1ErrorInvalidCustomMode        ZwlrOutputConfigurationHeadV1Error = 3
	ZwlrOutputConfigurationHeadV1ErrorInvalidTransform         ZwlrOutputConfigurationHeadV1Error = 4
	ZwlrOutputConfigurationHeadV1ErrorInvalidScale             ZwlrOutputConfigurationHeadV1Error = 5
	ZwlrOutputConfigurationHeadV1ErrorInvalidAdaptiveSyncState ZwlrOutputConfigurationHeadV1Error = 6
)

// ZwlrOutputConfigurationHeadV1Handler handles zwlr_output_configuration_head_v1 requests.
type ZwlrOutputConfigurationHeadV1Handler interface {
	SetMode(self *ZwlrOutputConfigurationHeadV1, mode *ZwlrOutputModeV1)
	SetCustomMode(self *ZwlrOutputConfigurationHeadV1, width int32, height int32, refresh int32)
	SetPosition(self *ZwlrOutputConfigurationHeadV1, x int32, y int32)
	SetTransform(self *ZwlrOutputConfigurationHeadV1, transform int32)
	SetScale(self *ZwlrOutputConfigurationHeadV1, scale server.Fixed)
	SetAdaptiveSync(self *ZwlrOutputConfigurationHeadV1, state uint32)
}

func NewZwlrOutputConfigurationHeadV1(c server.Client, version int32, id uint32, h ZwlrOutputConfigurationHeadV1Handler) (*ZwlrOutputConfigurationHeadV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for zwlr_output_configuration_head_v1")
	}
	var self *ZwlrOutputConfigurationHeadV1
	r, err := c.CreateResource(ZwlrOutputConfigurationHeadV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.SetMode(self, WrapZwlrOutputModeV1(args[0].Resource()))
		case 1:
			h.SetCustomMode(self, args[0].Int(), args[1].Int(), args[2].Int())
		case 2:
			h.SetPosition(self, args[0].Int(), args[1].Int())
		case 3:
			h.SetTransform(self, args[0].Int())
		case 4:
			h.SetScale(self, args[0].Fixed())
		case 5:
			h.SetAdaptiveSync(self, args[0].Uint())
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapZwlrOutputConfigurationHeadV1(r)
	r.Data = self
	return self, nil
}
func NewZwlrOutputConfigurationHeadV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(ZwlrOutputConfigurationHeadV1Interface, version, bind)
}
func resourceOf(v interface{ GetResource() *server.Resource }) *server.Resource {
	if v == nil {
		return nil
	}
	return v.GetResource()
}
func (self *ZwlrOutputManagerV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *ZwlrOutputHeadV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *ZwlrOutputModeV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *ZwlrOutputConfigurationV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *ZwlrOutputConfigurationHeadV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
