// Code generated by wlgen; DO NOT EDIT.
package xdgtoplevelicon

import (
	"fmt"
	wayland "github.com/bnema/purego-libwayland/protocol/wayland"
	xdgshell "github.com/bnema/purego-libwayland/protocol/xdgshell"
	"github.com/bnema/purego-libwayland/server"
)

var ToplevelIconManagerV1Interface *server.Interface
var ToplevelIconV1Interface *server.Interface

func init() {
	ToplevelIconManagerV1Interface = &server.Interface{Name: "xdg_toplevel_icon_manager_v1", Version: 1}
	ToplevelIconV1Interface = &server.Interface{Name: "xdg_toplevel_icon_v1", Version: 1}
	ToplevelIconManagerV1Interface.Requests = []server.Message{
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
		{Name: "create_icon", Signature: "n", Types: []*server.Interface{ToplevelIconV1Interface}},
		{Name: "set_icon", Signature: "o?o", Types: []*server.Interface{xdgshell.ToplevelInterface, ToplevelIconV1Interface}},
	}
	ToplevelIconManagerV1Interface.Events = []server.Message{
		{Name: "icon_size", Signature: "i", Types: []*server.Interface{nil}},
		{Name: "done", Signature: "", Types: []*server.Interface{}},
	}
	ToplevelIconV1Interface.Requests = []server.Message{
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
		{Name: "set_name", Signature: "s", Types: []*server.Interface{nil}},
		{Name: "add_buffer", Signature: "oi", Types: []*server.Interface{wayland.BufferInterface, nil}},
	}
	ToplevelIconV1Interface.Events = []server.Message{}
	if err := server.NewInterfaces(ToplevelIconManagerV1Interface, ToplevelIconV1Interface); err != nil {
		panic(err)
	}
}

// ToplevelIconManagerV1 interface to manage toplevel icons.
type ToplevelIconManagerV1 struct{ *server.Resource }

func WrapToplevelIconManagerV1(r *server.Resource) *ToplevelIconManagerV1 {
	if r == nil {
		return nil
	}
	return &ToplevelIconManagerV1{r}
}

const ToplevelIconManagerV1RequestDestroy uint32 = 0
const ToplevelIconManagerV1RequestCreateIcon uint32 = 1
const ToplevelIconManagerV1RequestSetIcon uint32 = 2
const ToplevelIconManagerV1EventIconSize uint32 = 0
const ToplevelIconManagerV1EventDone uint32 = 1

// ToplevelIconManagerV1Handler handles xdg_toplevel_icon_manager_v1 requests.
type ToplevelIconManagerV1Handler interface {
	Destroy(self *ToplevelIconManagerV1)
	CreateIcon(self *ToplevelIconManagerV1, id uint32)
	SetIcon(self *ToplevelIconManagerV1, toplevel *xdgshell.Toplevel, icon *ToplevelIconV1)
}

func NewToplevelIconManagerV1(c server.Client, version int32, id uint32, h ToplevelIconManagerV1Handler) (*ToplevelIconManagerV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for xdg_toplevel_icon_manager_v1")
	}
	var self *ToplevelIconManagerV1
	r, err := c.CreateResource(ToplevelIconManagerV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Destroy(self)
			self.Destroy()
		case 1:
			h.CreateIcon(self, args[0].NewID())
		case 2:
			h.SetIcon(self, xdgshell.WrapToplevel(args[0].Resource()), WrapToplevelIconV1(args[1].Resource()))
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapToplevelIconManagerV1(r)
	r.Data = self
	return self, nil
}

// SendIconSize describes a supported & preferred icon size.
func (self *ToplevelIconManagerV1) SendIconSize(size int32) {
	self.PostEvent(ToplevelIconManagerV1EventIconSize, server.Int(size))
}

// SendDone all information has been sent.
func (self *ToplevelIconManagerV1) SendDone() {
	self.PostEvent(ToplevelIconManagerV1EventDone)
}
func NewToplevelIconManagerV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(ToplevelIconManagerV1Interface, version, bind)
}

// ToplevelIconV1 a toplevel window icon.
type ToplevelIconV1 struct{ *server.Resource }

func WrapToplevelIconV1(r *server.Resource) *ToplevelIconV1 {
	if r == nil {
		return nil
	}
	return &ToplevelIconV1{r}
}

const ToplevelIconV1RequestDestroy uint32 = 0
const ToplevelIconV1RequestSetName uint32 = 1
const ToplevelIconV1RequestAddBuffer uint32 = 2

// ToplevelIconV1Error .
type ToplevelIconV1Error uint32

const (
	ToplevelIconV1ErrorInvalidBuffer ToplevelIconV1Error = 1
	ToplevelIconV1ErrorImmutable     ToplevelIconV1Error = 2
	ToplevelIconV1ErrorNoBuffer      ToplevelIconV1Error = 3
)

// ToplevelIconV1Handler handles xdg_toplevel_icon_v1 requests.
type ToplevelIconV1Handler interface {
	Destroy(self *ToplevelIconV1)
	SetName(self *ToplevelIconV1, iconName string)
	AddBuffer(self *ToplevelIconV1, buffer *wayland.Buffer, scale int32)
}

func NewToplevelIconV1(c server.Client, version int32, id uint32, h ToplevelIconV1Handler) (*ToplevelIconV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for xdg_toplevel_icon_v1")
	}
	var self *ToplevelIconV1
	r, err := c.CreateResource(ToplevelIconV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Destroy(self)
			self.Destroy()
		case 1:
			h.SetName(self, args[0].String())
		case 2:
			h.AddBuffer(self, wayland.WrapBuffer(args[0].Resource()), args[1].Int())
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapToplevelIconV1(r)
	r.Data = self
	return self, nil
}
func NewToplevelIconV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(ToplevelIconV1Interface, version, bind)
}
func resourceOf(v interface{ GetResource() *server.Resource }) *server.Resource {
	if v == nil {
		return nil
	}
	return v.GetResource()
}
func (self *ToplevelIconManagerV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *ToplevelIconV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
