// Code generated by wlgen; DO NOT EDIT.
package xdgsystembell

import (
	"fmt"
	wayland "github.com/bnema/purego-libwayland/protocol/wayland"
	"github.com/bnema/purego-libwayland/server"
)

var SystemBellV1Interface *server.Interface

func init() {
	SystemBellV1Interface = &server.Interface{Name: "xdg_system_bell_v1", Version: 1}
	SystemBellV1Interface.Requests = []server.Message{
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
		{Name: "ring", Signature: "?o", Types: []*server.Interface{wayland.SurfaceInterface}},
	}
	SystemBellV1Interface.Events = []server.Message{}
	if err := server.NewInterfaces(SystemBellV1Interface); err != nil {
		panic(err)
	}
}

// SystemBellV1 system bell.
type SystemBellV1 struct{ *server.Resource }

func WrapSystemBellV1(r *server.Resource) *SystemBellV1 {
	if r == nil {
		return nil
	}
	return &SystemBellV1{r}
}

const SystemBellV1RequestDestroy uint32 = 0
const SystemBellV1RequestRing uint32 = 1

// SystemBellV1Handler handles xdg_system_bell_v1 requests.
type SystemBellV1Handler interface {
	Destroy(self *SystemBellV1)
	Ring(self *SystemBellV1, surface *wayland.Surface)
}

func NewSystemBellV1(c server.Client, version int32, id uint32, h SystemBellV1Handler) (*SystemBellV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for xdg_system_bell_v1")
	}
	var self *SystemBellV1
	r, err := c.CreateResource(SystemBellV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Destroy(self)
			self.Destroy()
		case 1:
			h.Ring(self, wayland.WrapSurface(args[0].Resource()))
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapSystemBellV1(r)
	r.Data = self
	return self, nil
}
func NewSystemBellV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(SystemBellV1Interface, version, bind)
}
func resourceOf(v interface{ GetResource() *server.Resource }) *server.Resource {
	if v == nil {
		return nil
	}
	return v.GetResource()
}
func (self *SystemBellV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
