// Code generated by wlgen; DO NOT EDIT.
package relativepointer

import (
	"fmt"
	wayland "github.com/bnema/purego-libwayland/protocol/wayland"
	"github.com/bnema/purego-libwayland/server"
)

var ZwpRelativePointerManagerV1Interface *server.Interface
var ZwpRelativePointerV1Interface *server.Interface

func init() {
	ZwpRelativePointerManagerV1Interface = &server.Interface{Name: "zwp_relative_pointer_manager_v1", Version: 1}
	ZwpRelativePointerV1Interface = &server.Interface{Name: "zwp_relative_pointer_v1", Version: 1}
	ZwpRelativePointerManagerV1Interface.Requests = []server.Message{
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
		{Name: "get_relative_pointer", Signature: "no", Types: []*server.Interface{ZwpRelativePointerV1Interface, wayland.PointerInterface}},
	}
	ZwpRelativePointerManagerV1Interface.Events = []server.Message{}
	ZwpRelativePointerV1Interface.Requests = []server.Message{
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
	}
	ZwpRelativePointerV1Interface.Events = []server.Message{
		{Name: "relative_motion", Signature: "uuffff", Types: []*server.Interface{nil, nil, nil, nil, nil, nil}},
	}
	if err := server.NewInterfaces(ZwpRelativePointerManagerV1Interface, ZwpRelativePointerV1Interface); err != nil {
		panic(err)
	}
}

// ZwpRelativePointerManagerV1 get relative pointer objects.
type ZwpRelativePointerManagerV1 struct{ *server.Resource }

func WrapZwpRelativePointerManagerV1(r *server.Resource) *ZwpRelativePointerManagerV1 {
	if r == nil {
		return nil
	}
	return &ZwpRelativePointerManagerV1{r}
}

const ZwpRelativePointerManagerV1RequestDestroy uint32 = 0
const ZwpRelativePointerManagerV1RequestGetRelativePointer uint32 = 1

// ZwpRelativePointerManagerV1Handler handles zwp_relative_pointer_manager_v1 requests.
type ZwpRelativePointerManagerV1Handler interface {
	Destroy(self *ZwpRelativePointerManagerV1)
	GetRelativePointer(self *ZwpRelativePointerManagerV1, id uint32, pointer *wayland.Pointer)
}

func NewZwpRelativePointerManagerV1(c server.Client, version int32, id uint32, h ZwpRelativePointerManagerV1Handler) (*ZwpRelativePointerManagerV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for zwp_relative_pointer_manager_v1")
	}
	var self *ZwpRelativePointerManagerV1
	r, err := c.CreateResource(ZwpRelativePointerManagerV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Destroy(self)
			self.Destroy()
		case 1:
			h.GetRelativePointer(self, args[0].NewID(), wayland.WrapPointer(args[1].Resource()))
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapZwpRelativePointerManagerV1(r)
	r.Data = self
	return self, nil
}
func NewZwpRelativePointerManagerV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(ZwpRelativePointerManagerV1Interface, version, bind)
}

// ZwpRelativePointerV1 relative pointer object.
type ZwpRelativePointerV1 struct{ *server.Resource }

func WrapZwpRelativePointerV1(r *server.Resource) *ZwpRelativePointerV1 {
	if r == nil {
		return nil
	}
	return &ZwpRelativePointerV1{r}
}

const ZwpRelativePointerV1RequestDestroy uint32 = 0
const ZwpRelativePointerV1EventRelativeMotion uint32 = 0

// ZwpRelativePointerV1Handler handles zwp_relative_pointer_v1 requests.
type ZwpRelativePointerV1Handler interface {
	Destroy(self *ZwpRelativePointerV1)
}

func NewZwpRelativePointerV1(c server.Client, version int32, id uint32, h ZwpRelativePointerV1Handler) (*ZwpRelativePointerV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for zwp_relative_pointer_v1")
	}
	var self *ZwpRelativePointerV1
	r, err := c.CreateResource(ZwpRelativePointerV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Destroy(self)
			self.Destroy()
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapZwpRelativePointerV1(r)
	r.Data = self
	return self, nil
}

// SendRelativeMotion relative pointer motion.
func (self *ZwpRelativePointerV1) SendRelativeMotion(utimeHi uint32, utimeLo uint32, dx server.Fixed, dy server.Fixed, dxUnaccel server.Fixed, dyUnaccel server.Fixed) {
	self.PostEvent(ZwpRelativePointerV1EventRelativeMotion, server.Uint(utimeHi), server.Uint(utimeLo), server.FixedArg(dx), server.FixedArg(dy), server.FixedArg(dxUnaccel), server.FixedArg(dyUnaccel))
}
func NewZwpRelativePointerV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(ZwpRelativePointerV1Interface, version, bind)
}
func resourceOf(v interface{ GetResource() *server.Resource }) *server.Resource {
	if v == nil {
		return nil
	}
	return v.GetResource()
}
func (self *ZwpRelativePointerManagerV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *ZwpRelativePointerV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
