// Code generated by wlgen; DO NOT EDIT.
package fractionalscale

import (
	"fmt"
	wayland "github.com/bnema/purego-libwayland/protocol/wayland"
	"github.com/bnema/purego-libwayland/server"
)

var WpFractionalScaleManagerV1Interface *server.Interface
var WpFractionalScaleV1Interface *server.Interface

func init() {
	WpFractionalScaleManagerV1Interface = &server.Interface{Name: "wp_fractional_scale_manager_v1", Version: 1}
	WpFractionalScaleV1Interface = &server.Interface{Name: "wp_fractional_scale_v1", Version: 1}
	WpFractionalScaleManagerV1Interface.Requests = []server.Message{
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
		{Name: "get_fractional_scale", Signature: "no", Types: []*server.Interface{WpFractionalScaleV1Interface, wayland.SurfaceInterface}},
	}
	WpFractionalScaleManagerV1Interface.Events = []server.Message{}
	WpFractionalScaleV1Interface.Requests = []server.Message{
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
	}
	WpFractionalScaleV1Interface.Events = []server.Message{
		{Name: "preferred_scale", Signature: "u", Types: []*server.Interface{nil}},
	}
	if err := server.NewInterfaces(WpFractionalScaleManagerV1Interface, WpFractionalScaleV1Interface); err != nil {
		panic(err)
	}
}

// WpFractionalScaleManagerV1 fractional surface scale information.
type WpFractionalScaleManagerV1 struct{ *server.Resource }

func WrapWpFractionalScaleManagerV1(r *server.Resource) *WpFractionalScaleManagerV1 {
	if r == nil {
		return nil
	}
	return &WpFractionalScaleManagerV1{r}
}

const WpFractionalScaleManagerV1RequestDestroy uint32 = 0
const WpFractionalScaleManagerV1RequestGetFractionalScale uint32 = 1

// WpFractionalScaleManagerV1Error .
type WpFractionalScaleManagerV1Error uint32

const (
	WpFractionalScaleManagerV1ErrorFractionalScaleExists WpFractionalScaleManagerV1Error = 0
)

// WpFractionalScaleManagerV1Handler handles wp_fractional_scale_manager_v1 requests.
type WpFractionalScaleManagerV1Handler interface {
	Destroy(self *WpFractionalScaleManagerV1)
	GetFractionalScale(self *WpFractionalScaleManagerV1, id uint32, surface *wayland.Surface)
}

func NewWpFractionalScaleManagerV1(c server.Client, version int32, id uint32, h WpFractionalScaleManagerV1Handler) (*WpFractionalScaleManagerV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for wp_fractional_scale_manager_v1")
	}
	var self *WpFractionalScaleManagerV1
	r, err := c.CreateResource(WpFractionalScaleManagerV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Destroy(self)
			self.Destroy()
		case 1:
			h.GetFractionalScale(self, args[0].NewID(), wayland.WrapSurface(args[1].Resource()))
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapWpFractionalScaleManagerV1(r)
	r.Data = self
	return self, nil
}
func NewWpFractionalScaleManagerV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(WpFractionalScaleManagerV1Interface, version, bind)
}

// WpFractionalScaleV1 fractional scale interface to a wl_surface.
type WpFractionalScaleV1 struct{ *server.Resource }

func WrapWpFractionalScaleV1(r *server.Resource) *WpFractionalScaleV1 {
	if r == nil {
		return nil
	}
	return &WpFractionalScaleV1{r}
}

const WpFractionalScaleV1RequestDestroy uint32 = 0
const WpFractionalScaleV1EventPreferredScale uint32 = 0

// WpFractionalScaleV1Handler handles wp_fractional_scale_v1 requests.
type WpFractionalScaleV1Handler interface {
	Destroy(self *WpFractionalScaleV1)
}

func NewWpFractionalScaleV1(c server.Client, version int32, id uint32, h WpFractionalScaleV1Handler) (*WpFractionalScaleV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for wp_fractional_scale_v1")
	}
	var self *WpFractionalScaleV1
	r, err := c.CreateResource(WpFractionalScaleV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Destroy(self)
			self.Destroy()
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapWpFractionalScaleV1(r)
	r.Data = self
	return self, nil
}

// SendPreferredScale notify of new preferred scale.
func (self *WpFractionalScaleV1) SendPreferredScale(scale uint32) {
	self.PostEvent(WpFractionalScaleV1EventPreferredScale, server.Uint(scale))
}
func NewWpFractionalScaleV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(WpFractionalScaleV1Interface, version, bind)
}
func resourceOf(v interface{ GetResource() *server.Resource }) *server.Resource {
	if v == nil {
		return nil
	}
	return v.GetResource()
}
func (self *WpFractionalScaleManagerV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *WpFractionalScaleV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
