// Code generated by wlgen; DO NOT EDIT.
package xwaylandkeyboardgrab

import (
	"fmt"
	wayland "github.com/bnema/purego-libwayland/protocol/wayland"
	"github.com/bnema/purego-libwayland/server"
)

var ZwpXwaylandKeyboardGrabManagerV1Interface *server.Interface
var ZwpXwaylandKeyboardGrabV1Interface *server.Interface

func init() {
	ZwpXwaylandKeyboardGrabManagerV1Interface = &server.Interface{Name: "zwp_xwayland_keyboard_grab_manager_v1", Version: 1}
	ZwpXwaylandKeyboardGrabV1Interface = &server.Interface{Name: "zwp_xwayland_keyboard_grab_v1", Version: 1}
	ZwpXwaylandKeyboardGrabManagerV1Interface.Requests = []server.Message{
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
		{Name: "grab_keyboard", Signature: "noo", Types: []*server.Interface{ZwpXwaylandKeyboardGrabV1Interface, wayland.SurfaceInterface, wayland.SeatInterface}},
	}
	ZwpXwaylandKeyboardGrabManagerV1Interface.Events = []server.Message{}
	ZwpXwaylandKeyboardGrabV1Interface.Requests = []server.Message{
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
	}
	ZwpXwaylandKeyboardGrabV1Interface.Events = []server.Message{}
	if err := server.NewInterfaces(ZwpXwaylandKeyboardGrabManagerV1Interface, ZwpXwaylandKeyboardGrabV1Interface); err != nil {
		panic(err)
	}
}

// ZwpXwaylandKeyboardGrabManagerV1 context object for keyboard grab manager.
type ZwpXwaylandKeyboardGrabManagerV1 struct{ *server.Resource }

func WrapZwpXwaylandKeyboardGrabManagerV1(r *server.Resource) *ZwpXwaylandKeyboardGrabManagerV1 {
	if r == nil {
		return nil
	}
	return &ZwpXwaylandKeyboardGrabManagerV1{r}
}

const ZwpXwaylandKeyboardGrabManagerV1RequestDestroy uint32 = 0
const ZwpXwaylandKeyboardGrabManagerV1RequestGrabKeyboard uint32 = 1

// ZwpXwaylandKeyboardGrabManagerV1Handler handles zwp_xwayland_keyboard_grab_manager_v1 requests.
type ZwpXwaylandKeyboardGrabManagerV1Handler interface {
	Destroy(self *ZwpXwaylandKeyboardGrabManagerV1)
	GrabKeyboard(self *ZwpXwaylandKeyboardGrabManagerV1, id uint32, surface *wayland.Surface, seat *wayland.Seat)
}

func NewZwpXwaylandKeyboardGrabManagerV1(c server.Client, version int32, id uint32, h ZwpXwaylandKeyboardGrabManagerV1Handler) (*ZwpXwaylandKeyboardGrabManagerV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for zwp_xwayland_keyboard_grab_manager_v1")
	}
	var self *ZwpXwaylandKeyboardGrabManagerV1
	r, err := c.CreateResource(ZwpXwaylandKeyboardGrabManagerV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Destroy(self)
			self.Destroy()
		case 1:
			h.GrabKeyboard(self, args[0].NewID(), wayland.WrapSurface(args[1].Resource()), wayland.WrapSeat(args[2].Resource()))
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapZwpXwaylandKeyboardGrabManagerV1(r)
	r.Data = self
	return self, nil
}
func NewZwpXwaylandKeyboardGrabManagerV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(ZwpXwaylandKeyboardGrabManagerV1Interface, version, bind)
}

// ZwpXwaylandKeyboardGrabV1 interface for grabbing the keyboard.
type ZwpXwaylandKeyboardGrabV1 struct{ *server.Resource }

func WrapZwpXwaylandKeyboardGrabV1(r *server.Resource) *ZwpXwaylandKeyboardGrabV1 {
	if r == nil {
		return nil
	}
	return &ZwpXwaylandKeyboardGrabV1{r}
}

const ZwpXwaylandKeyboardGrabV1RequestDestroy uint32 = 0

// ZwpXwaylandKeyboardGrabV1Handler handles zwp_xwayland_keyboard_grab_v1 requests.
type ZwpXwaylandKeyboardGrabV1Handler interface {
	Destroy(self *ZwpXwaylandKeyboardGrabV1)
}

func NewZwpXwaylandKeyboardGrabV1(c server.Client, version int32, id uint32, h ZwpXwaylandKeyboardGrabV1Handler) (*ZwpXwaylandKeyboardGrabV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for zwp_xwayland_keyboard_grab_v1")
	}
	var self *ZwpXwaylandKeyboardGrabV1
	r, err := c.CreateResource(ZwpXwaylandKeyboardGrabV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Destroy(self)
			self.Destroy()
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapZwpXwaylandKeyboardGrabV1(r)
	r.Data = self
	return self, nil
}
func NewZwpXwaylandKeyboardGrabV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(ZwpXwaylandKeyboardGrabV1Interface, version, bind)
}
func resourceOf(v interface{ GetResource() *server.Resource }) *server.Resource {
	if v == nil {
		return nil
	}
	return v.GetResource()
}
func (self *ZwpXwaylandKeyboardGrabManagerV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *ZwpXwaylandKeyboardGrabV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
