// Code generated by wlgen; DO NOT EDIT.
package xdgtopleveltag

import (
	"fmt"
	xdgshell "github.com/bnema/purego-libwayland/protocol/xdgshell"
	"github.com/bnema/purego-libwayland/server"
)

var ToplevelTagManagerV1Interface *server.Interface

func init() {
	ToplevelTagManagerV1Interface = &server.Interface{Name: "xdg_toplevel_tag_manager_v1", Version: 1}
	ToplevelTagManagerV1Interface.Requests = []server.Message{
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
		{Name: "set_toplevel_tag", Signature: "os", Types: []*server.Interface{xdgshell.ToplevelInterface, nil}},
		{Name: "set_toplevel_description", Signature: "os", Types: []*server.Interface{xdgshell.ToplevelInterface, nil}},
	}
	ToplevelTagManagerV1Interface.Events = []server.Message{}
	if err := server.NewInterfaces(ToplevelTagManagerV1Interface); err != nil {
		panic(err)
	}
}

// ToplevelTagManagerV1 protocol for setting toplevel tags.
type ToplevelTagManagerV1 struct{ *server.Resource }

func WrapToplevelTagManagerV1(r *server.Resource) *ToplevelTagManagerV1 {
	if r == nil {
		return nil
	}
	return &ToplevelTagManagerV1{r}
}

const ToplevelTagManagerV1RequestDestroy uint32 = 0
const ToplevelTagManagerV1RequestSetToplevelTag uint32 = 1
const ToplevelTagManagerV1RequestSetToplevelDescription uint32 = 2

// ToplevelTagManagerV1Handler handles xdg_toplevel_tag_manager_v1 requests.
type ToplevelTagManagerV1Handler interface {
	Destroy(self *ToplevelTagManagerV1)
	SetToplevelTag(self *ToplevelTagManagerV1, toplevel *xdgshell.Toplevel, tag string)
	SetToplevelDescription(self *ToplevelTagManagerV1, toplevel *xdgshell.Toplevel, description string)
}

func NewToplevelTagManagerV1(c server.Client, version int32, id uint32, h ToplevelTagManagerV1Handler) (*ToplevelTagManagerV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for xdg_toplevel_tag_manager_v1")
	}
	var self *ToplevelTagManagerV1
	r, err := c.CreateResource(ToplevelTagManagerV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Destroy(self)
			self.Destroy()
		case 1:
			h.SetToplevelTag(self, xdgshell.WrapToplevel(args[0].Resource()), args[1].String())
		case 2:
			h.SetToplevelDescription(self, xdgshell.WrapToplevel(args[0].Resource()), args[1].String())
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapToplevelTagManagerV1(r)
	r.Data = self
	return self, nil
}
func NewToplevelTagManagerV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(ToplevelTagManagerV1Interface, version, bind)
}
func resourceOf(v interface{ GetResource() *server.Resource }) *server.Resource {
	if v == nil {
		return nil
	}
	return v.GetResource()
}
func (self *ToplevelTagManagerV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
