// Code generated by wlgen; DO NOT EDIT.
package cursorshape

import (
	"fmt"
	tabletv2 "github.com/bnema/purego-libwayland/protocol/tabletv2"
	wayland "github.com/bnema/purego-libwayland/protocol/wayland"
	"github.com/bnema/purego-libwayland/server"
)

var WpCursorShapeManagerV1Interface *server.Interface
var WpCursorShapeDeviceV1Interface *server.Interface

func init() {
	WpCursorShapeManagerV1Interface = &server.Interface{Name: "wp_cursor_shape_manager_v1", Version: 2}
	WpCursorShapeDeviceV1Interface = &server.Interface{Name: "wp_cursor_shape_device_v1", Version: 2}
	WpCursorShapeManagerV1Interface.Requests = []server.Message{
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
		{Name: "get_pointer", Signature: "no", Types: []*server.Interface{WpCursorShapeDeviceV1Interface, wayland.PointerInterface}},
		{Name: "get_tablet_tool_v2", Signature: "no", Types: []*server.Interface{WpCursorShapeDeviceV1Interface, tabletv2.ZwpTabletToolV2Interface}},
	}
	WpCursorShapeManagerV1Interface.Events = []server.Message{}
	WpCursorShapeDeviceV1Interface.Requests = []server.Message{
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
		{Name: "set_shape", Signature: "uu", Types: []*server.Interface{nil, nil}},
	}
	WpCursorShapeDeviceV1Interface.Events = []server.Message{}
	if err := server.NewInterfaces(WpCursorShapeManagerV1Interface, WpCursorShapeDeviceV1Interface); err != nil {
		panic(err)
	}
}

// WpCursorShapeManagerV1 cursor shape manager.
type WpCursorShapeManagerV1 struct{ *server.Resource }

func WrapWpCursorShapeManagerV1(r *server.Resource) *WpCursorShapeManagerV1 {
	if r == nil {
		return nil
	}
	return &WpCursorShapeManagerV1{r}
}

const WpCursorShapeManagerV1RequestDestroy uint32 = 0
const WpCursorShapeManagerV1RequestGetPointer uint32 = 1
const WpCursorShapeManagerV1RequestGetTabletToolV2 uint32 = 2

// WpCursorShapeManagerV1Handler handles wp_cursor_shape_manager_v1 requests.
type WpCursorShapeManagerV1Handler interface {
	Destroy(self *WpCursorShapeManagerV1)
	GetPointer(self *WpCursorShapeManagerV1, cursorShapeDevice uint32, pointer *wayland.Pointer)
	GetTabletToolV2(self *WpCursorShapeManagerV1, cursorShapeDevice uint32, tabletTool *tabletv2.ZwpTabletToolV2)
}

func NewWpCursorShapeManagerV1(c server.Client, version int32, id uint32, h WpCursorShapeManagerV1Handler) (*WpCursorShapeManagerV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for wp_cursor_shape_manager_v1")
	}
	var self *WpCursorShapeManagerV1
	r, err := c.CreateResource(WpCursorShapeManagerV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Destroy(self)
			self.Destroy()
		case 1:
			h.GetPointer(self, args[0].NewID(), wayland.WrapPointer(args[1].Resource()))
		case 2:
			h.GetTabletToolV2(self, args[0].NewID(), tabletv2.WrapZwpTabletToolV2(args[1].Resource()))
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapWpCursorShapeManagerV1(r)
	r.Data = self
	return self, nil
}
func NewWpCursorShapeManagerV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(WpCursorShapeManagerV1Interface, version, bind)
}

// WpCursorShapeDeviceV1 cursor shape for a device.
type WpCursorShapeDeviceV1 struct{ *server.Resource }

func WrapWpCursorShapeDeviceV1(r *server.Resource) *WpCursorShapeDeviceV1 {
	if r == nil {
		return nil
	}
	return &WpCursorShapeDeviceV1{r}
}

const WpCursorShapeDeviceV1RequestDestroy uint32 = 0
const WpCursorShapeDeviceV1RequestSetShape uint32 = 1

// WpCursorShapeDeviceV1Shape cursor shapes.
type WpCursorShapeDeviceV1Shape uint32

const (
	WpCursorShapeDeviceV1ShapeDefault      WpCursorShapeDeviceV1Shape = 1
	WpCursorShapeDeviceV1ShapeContextMenu  WpCursorShapeDeviceV1Shape = 2
	WpCursorShapeDeviceV1ShapeHelp         WpCursorShapeDeviceV1Shape = 3
	WpCursorShapeDeviceV1ShapePointer      WpCursorShapeDeviceV1Shape = 4
	WpCursorShapeDeviceV1ShapeProgress     WpCursorShapeDeviceV1Shape = 5
	WpCursorShapeDeviceV1ShapeWait         WpCursorShapeDeviceV1Shape = 6
	WpCursorShapeDeviceV1ShapeCell         WpCursorShapeDeviceV1Shape = 7
	WpCursorShapeDeviceV1ShapeCrosshair    WpCursorShapeDeviceV1Shape = 8
	WpCursorShapeDeviceV1ShapeText         WpCursorShapeDeviceV1Shape = 9
	WpCursorShapeDeviceV1ShapeVerticalText WpCursorShapeDeviceV1Shape = 10
	WpCursorShapeDeviceV1ShapeAlias        WpCursorShapeDeviceV1Shape = 11
	WpCursorShapeDeviceV1ShapeCopy         WpCursorShapeDeviceV1Shape = 12
	WpCursorShapeDeviceV1ShapeMove         WpCursorShapeDeviceV1Shape = 13
	WpCursorShapeDeviceV1ShapeNoDrop       WpCursorShapeDeviceV1Shape = 14
	WpCursorShapeDeviceV1ShapeNotAllowed   WpCursorShapeDeviceV1Shape = 15
	WpCursorShapeDeviceV1ShapeGrab         WpCursorShapeDeviceV1Shape = 16
	WpCursorShapeDeviceV1ShapeGrabbing     WpCursorShapeDeviceV1Shape = 17
	WpCursorShapeDeviceV1ShapeEResize      WpCursorShapeDeviceV1Shape = 18
	WpCursorShapeDeviceV1ShapeNResize      WpCursorShapeDeviceV1Shape = 19
	WpCursorShapeDeviceV1ShapeNeResize     WpCursorShapeDeviceV1Shape = 20
	WpCursorShapeDeviceV1ShapeNwResize     WpCursorShapeDeviceV1Shape = 21
	WpCursorShapeDeviceV1ShapeSResize      WpCursorShapeDeviceV1Shape = 22
	WpCursorShapeDeviceV1ShapeSeResize     WpCursorShapeDeviceV1Shape = 23
	WpCursorShapeDeviceV1ShapeSwResize     WpCursorShapeDeviceV1Shape = 24
	WpCursorShapeDeviceV1ShapeWResize      WpCursorShapeDeviceV1Shape = 25
	WpCursorShapeDeviceV1ShapeEwResize     WpCursorShapeDeviceV1Shape = 26
	WpCursorShapeDeviceV1ShapeNsResize     WpCursorShapeDeviceV1Shape = 27
	WpCursorShapeDeviceV1ShapeNeswResize   WpCursorShapeDeviceV1Shape = 28
	WpCursorShapeDeviceV1ShapeNwseResize   WpCursorShapeDeviceV1Shape = 29
	WpCursorShapeDeviceV1ShapeColResize    WpCursorShapeDeviceV1Shape = 30
	WpCursorShapeDeviceV1ShapeRowResize    WpCursorShapeDeviceV1Shape = 31
	WpCursorShapeDeviceV1ShapeAllScroll    WpCursorShapeDeviceV1Shape = 32
	WpCursorShapeDeviceV1ShapeZoomIn       WpCursorShapeDeviceV1Shape = 33
	WpCursorShapeDeviceV1ShapeZoomOut      WpCursorShapeDeviceV1Shape = 34
	WpCursorShapeDeviceV1ShapeDndAsk       WpCursorShapeDeviceV1Shape = 35
	WpCursorShapeDeviceV1ShapeAllResize    WpCursorShapeDeviceV1Shape = 36
)

// WpCursorShapeDeviceV1Error .
type WpCursorShapeDeviceV1Error uint32

const (
	WpCursorShapeDeviceV1ErrorInvalidShape WpCursorShapeDeviceV1Error = 1
)

// WpCursorShapeDeviceV1Handler handles wp_cursor_shape_device_v1 requests.
type WpCursorShapeDeviceV1Handler interface {
	Destroy(self *WpCursorShapeDeviceV1)
	SetShape(self *WpCursorShapeDeviceV1, serial uint32, shape uint32)
}

func NewWpCursorShapeDeviceV1(c server.Client, version int32, id uint32, h WpCursorShapeDeviceV1Handler) (*WpCursorShapeDeviceV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for wp_cursor_shape_device_v1")
	}
	var self *WpCursorShapeDeviceV1
	r, err := c.CreateResource(WpCursorShapeDeviceV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Destroy(self)
			self.Destroy()
		case 1:
			h.SetShape(self, args[0].Uint(), args[1].Uint())
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapWpCursorShapeDeviceV1(r)
	r.Data = self
	return self, nil
}
func NewWpCursorShapeDeviceV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(WpCursorShapeDeviceV1Interface, version, bind)
}
func resourceOf(v interface{ GetResource() *server.Resource }) *server.Resource {
	if v == nil {
		return nil
	}
	return v.GetResource()
}
func (self *WpCursorShapeManagerV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *WpCursorShapeDeviceV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
