// Code generated by wlgen; DO NOT EDIT.
package committiming

import (
	"fmt"
	wayland "github.com/bnema/purego-libwayland/protocol/wayland"
	"github.com/bnema/purego-libwayland/server"
)

var WpCommitTimingManagerV1Interface *server.Interface
var WpCommitTimerV1Interface *server.Interface

func init() {
	WpCommitTimingManagerV1Interface = &server.Interface{Name: "wp_commit_timing_manager_v1", Version: 1}
	WpCommitTimerV1Interface = &server.Interface{Name: "wp_commit_timer_v1", Version: 1}
	WpCommitTimingManagerV1Interface.Requests = []server.Message{
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
		{Name: "get_timer", Signature: "no", Types: []*server.Interface{WpCommitTimerV1Interface, wayland.SurfaceInterface}},
	}
	WpCommitTimingManagerV1Interface.Events = []server.Message{}
	WpCommitTimerV1Interface.Requests = []server.Message{
		{Name: "set_timestamp", Signature: "uuu", Types: []*server.Interface{nil, nil, nil}},
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
	}
	WpCommitTimerV1Interface.Events = []server.Message{}
	if err := server.NewInterfaces(WpCommitTimingManagerV1Interface, WpCommitTimerV1Interface); err != nil {
		panic(err)
	}
}

// WpCommitTimingManagerV1 commit timing.
type WpCommitTimingManagerV1 struct{ *server.Resource }

func WrapWpCommitTimingManagerV1(r *server.Resource) *WpCommitTimingManagerV1 {
	if r == nil {
		return nil
	}
	return &WpCommitTimingManagerV1{r}
}

const WpCommitTimingManagerV1RequestDestroy uint32 = 0
const WpCommitTimingManagerV1RequestGetTimer uint32 = 1

// WpCommitTimingManagerV1Error .
type WpCommitTimingManagerV1Error uint32

const (
	WpCommitTimingManagerV1ErrorCommitTimerExists WpCommitTimingManagerV1Error = 0
)

// WpCommitTimingManagerV1Handler handles wp_commit_timing_manager_v1 requests.
type WpCommitTimingManagerV1Handler interface {
	Destroy(self *WpCommitTimingManagerV1)
	GetTimer(self *WpCommitTimingManagerV1, id uint32, surface *wayland.Surface)
}

func NewWpCommitTimingManagerV1(c server.Client, version int32, id uint32, h WpCommitTimingManagerV1Handler) (*WpCommitTimingManagerV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for wp_commit_timing_manager_v1")
	}
	var self *WpCommitTimingManagerV1
	r, err := c.CreateResource(WpCommitTimingManagerV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Destroy(self)
			self.Destroy()
		case 1:
			h.GetTimer(self, args[0].NewID(), wayland.WrapSurface(args[1].Resource()))
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapWpCommitTimingManagerV1(r)
	r.Data = self
	return self, nil
}
func NewWpCommitTimingManagerV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(WpCommitTimingManagerV1Interface, version, bind)
}

// WpCommitTimerV1 Surface commit timer.
type WpCommitTimerV1 struct{ *server.Resource }

func WrapWpCommitTimerV1(r *server.Resource) *WpCommitTimerV1 {
	if r == nil {
		return nil
	}
	return &WpCommitTimerV1{r}
}

const WpCommitTimerV1RequestSetTimestamp uint32 = 0
const WpCommitTimerV1RequestDestroy uint32 = 1

// WpCommitTimerV1Error .
type WpCommitTimerV1Error uint32

const (
	WpCommitTimerV1ErrorInvalidTimestamp WpCommitTimerV1Error = 0
	WpCommitTimerV1ErrorTimestampExists  WpCommitTimerV1Error = 1
	WpCommitTimerV1ErrorSurfaceDestroyed WpCommitTimerV1Error = 2
)

// WpCommitTimerV1Handler handles wp_commit_timer_v1 requests.
type WpCommitTimerV1Handler interface {
	SetTimestamp(self *WpCommitTimerV1, tvSecHi uint32, tvSecLo uint32, tvNsec uint32)
	Destroy(self *WpCommitTimerV1)
}

func NewWpCommitTimerV1(c server.Client, version int32, id uint32, h WpCommitTimerV1Handler) (*WpCommitTimerV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for wp_commit_timer_v1")
	}
	var self *WpCommitTimerV1
	r, err := c.CreateResource(WpCommitTimerV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.SetTimestamp(self, args[0].Uint(), args[1].Uint(), args[2].Uint())
		case 1:
			h.Destroy(self)
			self.Destroy()
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapWpCommitTimerV1(r)
	r.Data = self
	return self, nil
}
func NewWpCommitTimerV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(WpCommitTimerV1Interface, version, bind)
}
func resourceOf(v interface{ GetResource() *server.Resource }) *server.Resource {
	if v == nil {
		return nil
	}
	return v.GetResource()
}
func (self *WpCommitTimingManagerV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *WpCommitTimerV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
