// Code generated by wlgen; DO NOT EDIT.
package virtualkeyboard

import (
	"fmt"
	wayland "github.com/bnema/purego-libwayland/protocol/wayland"
	"github.com/bnema/purego-libwayland/server"
)

var ZwpVirtualKeyboardV1Interface *server.Interface
var ZwpVirtualKeyboardManagerV1Interface *server.Interface

func init() {
	ZwpVirtualKeyboardV1Interface = &server.Interface{Name: "zwp_virtual_keyboard_v1", Version: 1}
	ZwpVirtualKeyboardManagerV1Interface = &server.Interface{Name: "zwp_virtual_keyboard_manager_v1", Version: 1}
	ZwpVirtualKeyboardV1Interface.Requests = []server.Message{
		{Name: "keymap", Signature: "uhu", Types: []*server.Interface{nil, nil, nil}},
		{Name: "key", Signature: "uuu", Types: []*server.Interface{nil, nil, nil}},
		{Name: "modifiers", Signature: "uuuu", Types: []*server.Interface{nil, nil, nil, nil}},
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
	}
	ZwpVirtualKeyboardV1Interface.Events = []server.Message{}
	ZwpVirtualKeyboardManagerV1Interface.Requests = []server.Message{
		{Name: "create_virtual_keyboard", Signature: "on", Types: []*server.Interface{wayland.SeatInterface, ZwpVirtualKeyboardV1Interface}},
	}
	ZwpVirtualKeyboardManagerV1Interface.Events = []server.Message{}
	if err := server.NewInterfaces(ZwpVirtualKeyboardV1Interface, ZwpVirtualKeyboardManagerV1Interface); err != nil {
		panic(err)
	}
}

// ZwpVirtualKeyboardV1 virtual keyboard.
type ZwpVirtualKeyboardV1 struct{ *server.Resource }

func WrapZwpVirtualKeyboardV1(r *server.Resource) *ZwpVirtualKeyboardV1 {
	if r == nil {
		return nil
	}
	return &ZwpVirtualKeyboardV1{r}
}

const ZwpVirtualKeyboardV1RequestKeymap uint32 = 0
const ZwpVirtualKeyboardV1RequestKey uint32 = 1
const ZwpVirtualKeyboardV1RequestModifiers uint32 = 2
const ZwpVirtualKeyboardV1RequestDestroy uint32 = 3

// ZwpVirtualKeyboardV1Error .
type ZwpVirtualKeyboardV1Error uint32

const (
	ZwpVirtualKeyboardV1ErrorNoKeymap ZwpVirtualKeyboardV1Error = 0
)

// ZwpVirtualKeyboardV1Handler handles zwp_virtual_keyboard_v1 requests.
type ZwpVirtualKeyboardV1Handler interface {
	Keymap(self *ZwpVirtualKeyboardV1, format uint32, fd int, size uint32)
	Key(self *ZwpVirtualKeyboardV1, time uint32, key uint32, state uint32)
	Modifiers(self *ZwpVirtualKeyboardV1, modsDepressed uint32, modsLatched uint32, modsLocked uint32, group uint32)
	Destroy(self *ZwpVirtualKeyboardV1)
}

func NewZwpVirtualKeyboardV1(c server.Client, version int32, id uint32, h ZwpVirtualKeyboardV1Handler) (*ZwpVirtualKeyboardV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for zwp_virtual_keyboard_v1")
	}
	var self *ZwpVirtualKeyboardV1
	r, err := c.CreateResource(ZwpVirtualKeyboardV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Keymap(self, args[0].Uint(), args[1].Fd(), args[2].Uint())
		case 1:
			h.Key(self, args[0].Uint(), args[1].Uint(), args[2].Uint())
		case 2:
			h.Modifiers(self, args[0].Uint(), args[1].Uint(), args[2].Uint(), args[3].Uint())
		case 3:
			h.Destroy(self)
			self.Destroy()
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapZwpVirtualKeyboardV1(r)
	r.Data = self
	return self, nil
}
func NewZwpVirtualKeyboardV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(ZwpVirtualKeyboardV1Interface, version, bind)
}

// ZwpVirtualKeyboardManagerV1 virtual keyboard manager.
type ZwpVirtualKeyboardManagerV1 struct{ *server.Resource }

func WrapZwpVirtualKeyboardManagerV1(r *server.Resource) *ZwpVirtualKeyboardManagerV1 {
	if r == nil {
		return nil
	}
	return &ZwpVirtualKeyboardManagerV1{r}
}

const ZwpVirtualKeyboardManagerV1RequestCreateVirtualKeyboard uint32 = 0

// ZwpVirtualKeyboardManagerV1Error .
type ZwpVirtualKeyboardManagerV1Error uint32

const (
	ZwpVirtualKeyboardManagerV1ErrorUnauthorized ZwpVirtualKeyboardManagerV1Error = 0
)

// ZwpVirtualKeyboardManagerV1Handler handles zwp_virtual_keyboard_manager_v1 requests.
type ZwpVirtualKeyboardManagerV1Handler interface {
	CreateVirtualKeyboard(self *ZwpVirtualKeyboardManagerV1, seat *wayland.Seat, id uint32)
}

func NewZwpVirtualKeyboardManagerV1(c server.Client, version int32, id uint32, h ZwpVirtualKeyboardManagerV1Handler) (*ZwpVirtualKeyboardManagerV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for zwp_virtual_keyboard_manager_v1")
	}
	var self *ZwpVirtualKeyboardManagerV1
	r, err := c.CreateResource(ZwpVirtualKeyboardManagerV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.CreateVirtualKeyboard(self, wayland.WrapSeat(args[0].Resource()), args[1].NewID())
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapZwpVirtualKeyboardManagerV1(r)
	r.Data = self
	return self, nil
}
func NewZwpVirtualKeyboardManagerV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(ZwpVirtualKeyboardManagerV1Interface, version, bind)
}
func resourceOf(v interface{ GetResource() *server.Resource }) *server.Resource {
	if v == nil {
		return nil
	}
	return v.GetResource()
}
func (self *ZwpVirtualKeyboardV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *ZwpVirtualKeyboardManagerV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
